Formula review statistics
openstax/cnx-recipes pull request #2626
Opened 2020-08-17 13:26 UTC by ajluk

Issue: #2617

2020-08-17 14:53 UTC, ajluk commented on styles/designs/corn/parts/_caption-components.scss
> +        break-inside: enum('ValueSet:::OPTIONAL'), //used in Tables in Formula Review
I have added this property, because I have found spot where long table caption jumped to the next column: 
![image](https://user-images.githubusercontent.com/55203598/90409963-17686080-e0aa-11ea-9fd0-8e64db5aa1f1.png)
Here is how it looks after: 
![image](https://user-images.githubusercontent.com/55203598/90410021-28b16d00-e0aa-11ea-9a95-04ee65dfc0b8.png)

2020-08-20 08:24 UTC, wilkus27 requested changes

2020-08-20 08:24 UTC, wilkus27 commented on styles/designs/corn/parts/_caption-components.scss
> +        break-inside: enum('ValueSet:::OPTIONAL'), //used in Tables in Formula Review
I think tables should be centered. They are left aligned at this moment, based on the screenshots.

2020-08-20 08:24 UTC, wilkus27 commented on styles/designs/corn/parts/_eoc-shapes.scss
> +@include create_shape('corn:::FormulaReviewShape',(
I think it would be better to add name to this shape related with its specific features. Otherwise we can't reuse it for other modules which should be displayed as Formula Review. So in two columns layout with text going down not to the right. I don't know, maybe `TwoColumnsVerticalEocShape`? @Stackblocks do you have other ideas?

2020-08-20 13:50 UTC, Stackblocks commented on styles/designs/corn/parts/_eoc-shapes.scss
> +@include create_shape('corn:::FormulaReviewShape',(
I agree that a functionally descriptive name with a comment like `//used for Formula Review` is the way to go.

`TwoColumnVerticalEocShape` seems like a good option to me!

2020-08-21 08:43 UTC, ajluk commented on styles/designs/corn/parts/_eoc-components.scss
> +$EoCSection__Container: empty_wrapper(EoCSectionContainer, ' > section');
Yes, good point! Thank you Natalia!

2020-08-21 08:46 UTC, ajluk commented on styles/designs/corn/parts/_eoc-shapes.scss
> +@include create_shape('corn:::FormulaReviewShape',(
Thank you both! I agree the name should be more descriptive.

2020-08-25 10:05 UTC, wilkus27 approved these changes

2020-08-27 12:44 UTC, merged