Circled lists issue
openstax/cnx-recipes pull request #2646
Opened 2020-08-20 14:53 UTC by ajluk

Issue: #2630

2020-08-20 15:20 UTC, ajluk commented on recipes/books/calculus/_config.scss
> +  (selector: ' > ol.circled:first-child'),
I have added this class to `$Config_FirstElements` to cover first circled lists children of problem containers. When the basic specs for problem containers are added these lists broken to another line line look like this (they jump over the problem number):
![image](https://user-images.githubusercontent.com/55203598/90790425-5693ed00-e308-11ea-9cc2-954d549fde16.png)
I have also couldn't use the specs for Images and Tables, because then the lists are little lower than the problem number: 
![image](https://user-images.githubusercontent.com/55203598/90790673-9eb30f80-e308-11ea-8d55-9c39512b0668.png)
Only one property can be used there `vertical align: bottom` without top padding. I couldn't also applied this property to "regular" problem containers because then the math in para wouldn't be in one line with the problem number. It only woks in the Answer Key (I'm not sure why exactly).

2020-08-20 15:22 UTC, ajluk commented on recipes/mixins/_modify.scss
> +            #{$element} {
I have modified the existing mixin for adding first element class instead of creating a new one. Let me know what do you think about it?

2020-08-20 15:29 UTC, ajluk commented on recipes/mixins/_modify.scss
>      @each $page in $Config_BookCompositePages {
I have also modified this mixin, but it has s defect that this change affects output css files for all books. I think it can't done any harm, because they don't have the `first-circled-list-element` class util it is added in the `config.scss file`. But let me know what are your thought about that solution.

2020-08-20 15:29 UTC, ajluk commented on recipes/mixins/_modify.scss
> +          }
See my comment above.

2020-08-20 15:30 UTC, ajluk commented on styles/templates/template2/parts/_answerkey-settings.scss
> -            vertical-align: bottom,
I have removes this property, because it wasn't needed any longer.

2020-08-20 15:35 UTC, ajluk commented on recipes/output/calculus.css
> +
In the corn theme books this lines are added as well. They are missing in the rest of the books output css files.

2020-08-25 13:29 UTC, brittany-johnson commented on recipes/mixins/_modify.scss
> +            #{$element} {
Hello! @wilkus27 I'm going to summarize how I understand your suggestion above to make sure that I understand you correctly. Please let me know if I got this right: 

- Add an optional key to the `$Config_FirstElements` map. 
- In this optional key, we will specify the element type. 
- We will then use the element type specified in the map to add the class instead of using `ol.circled:first-child`

If this is correct, then I agree. I think its always a good idea to make solutions that we can reuse!

2020-08-25 13:30 UTC, brittany-johnson commented on recipes/mixins/_modify.scss
> +            #{$element} {
@ajluk If you go with this solution, please re-assign me for review once it's implemented. Thank you!

2020-08-26 14:18 UTC, ajluk commented on styles/designs/corn/parts/_exercises-shapes.scss
> +                                                        map-merge($Table__Head, (
Yes, definitely!

2020-08-26 14:32 UTC, wilkus27 commented on recipes/mixins/_modify.scss
> +            #{$element} {
@brittany-johnson Yes, this is what I meant. :slightly_smiling_face:

2020-08-26 17:18 UTC, ajluk commented on recipes/books/_common-stuff.scss
> +$ConfighasFirstInlineListElement: false;
I have created this config conditional to use it in the if statement, where I couldn't use `elementType` condition.

2020-08-26 17:23 UTC, ajluk commented on recipes/mixins/_modify.scss
> +        @if $ConfighasFirstInlineListElement == true {
The config I have created at the beginning is used in this mixin where I couldn't use `$type == inlineList`. I've got errors that it is undefined for this mixin. Let me know if this solution is acceptable.

2020-08-26 17:29 UTC, ajluk commented on recipes/mixins/_modify.scss
> +            #{$element} {
@wilkus27 thank you for all your suggestions! :heart:  I have applied the requested changes. @brittany-johnson @Stackblocks  Let me know what do you think as well.

2020-08-27 11:55 UTC, ajluk commented on recipes/books/calculus/_config.scss
> +  (selector: ' > .circled:first-child', elementType: inlineList),
I have also changed this selector to cover both `ol` and `ul` circled lists.

2020-08-31 17:26 UTC, brittany-johnson commented on styles/designs/corn/parts/_exercises-shapes.scss
> +                                                        map-merge($Table__Head, (
I was also thinking that when reviewing, very large shape 😭

2020-09-01 09:22 UTC, wilkus27 requested changes

2020-09-01 09:22 UTC, wilkus27 commented on recipes/mixins/_modify.scss
> +      }
I'm not sure if it's necessary to create new config. I think it would be better to use one condition everywhere. Either `$Config_hasFirstInlineListElement` or `$elementType`. Both telling us that there is inline list at the beginning.

2020-09-02 11:51 UTC, wilkus27 commented on recipes/mixins/_modify.scss
> +      }
As we discussed in this case it's hard to use `$elementType` key because config `$Config_FirstElements` has nested maps. To extract it we need to use loop `each` what causes a lot of repetitions. So let's keep both condition. :sunglasses:

2020-09-02 11:52 UTC, wilkus27 approved these changes

2020-09-02 13:26 UTC, merged