Clean up titles corn
openstax/cnx-recipes pull request #2667
Opened 2020-08-24 08:46 UTC by ajluk

Issue: #2445

2020-08-24 10:50 UTC, ajluk commented on styles/designs/common/pdf/_page-breaks.scss
> +}
I have moved those to `page-breaks.scss file`, but these are specific only for corn theme. Maybe a better solution could be to create a separate `page-break.scss` file for corn and carnival or leave these properties in the components? Let me know what do you think.

2020-08-24 10:51 UTC, ajluk commented on styles/designs/corn/parts/_titles-shapes.scss
> +                $H1,
I have added the H1 title here to make this shape cover the Answer Key as well.

2020-08-24 10:53 UTC, ajluk commented on styles/designs/corn/parts/_answerkey-shapes.scss
> -            $H2,
I have removed H1, H2, H3 titles from this shape, because title shape can cover them now.

2020-08-28 14:48 UTC, ajluk commented on styles/designs/common/pdf/_page-breaks.scss
> +}
I have moved those to page-breaks.scss file, but these are specific only for corn theme. Maybe a better solution could be to create a separate page-break.scss file for corn and carnival or leave these properties in the components? Let me know what do you think.

2020-08-31 18:48 UTC, brittany-johnson commented on styles/designs/common/pdf/_page-breaks.scss
> +}
I think we should keep the `common` page-break file for the library-wide elements, but for elements like the ones above, we could have a page-break file for corn that imports the common page break file. What do you think? 

The reason why we opted to have a file just for page breaks is that in the past with oer.exports, the page breaks were scattered all over the repo and it was difficult to debug.

2020-09-01 09:44 UTC, wilkus27 requested changes

2020-09-01 09:44 UTC, wilkus27 commented on styles/designs/common/pdf/_page-breaks.scss
> +}
I think it's a very good idea. Everything will be clear and such solution will not have an impact on Carnival theme. 

@ajluk I have one more question. Is it necessary to use specific classes? 
For example here:
![image](https://user-images.githubusercontent.com/40228854/91832988-62f04200-ec46-11ea-9b3f-62c9d7a993ae.png)

Doesn't first selector cover two others marked by arrow?

2020-09-02 12:46 UTC, wilkus27 requested changes

2020-09-02 12:46 UTC, wilkus27 commented on styles/designs/corn/pdf/_page-breaks.scss
> +}
@ajluk In my last comment I meant classes next to `section`:

![image](https://user-images.githubusercontent.com/40228854/91982585-c0f65580-ed2a-11ea-957b-2e462143b3ca.png)

My question was, is it necesarry to add classes if in the first line it is applied to all sections. It should cover also those with `.writing` and `.everyday`

2020-09-02 14:58 UTC, ajluk commented on styles/designs/corn/pdf/_page-breaks.scss
> +.os-eoc.os-bring-together-exercises-container > section.bring-together-exercises > p {
I have also added selectors for paragraphs present in Statistics books. These aren't styled differently as in the other books from corn, but also needed these page break properties:
![image](https://user-images.githubusercontent.com/55203598/92000110-6fa39180-ed3d-11ea-92d9-c2fc13fd4be8.png)
![image](https://user-images.githubusercontent.com/55203598/92000159-7cc08080-ed3d-11ea-884c-c9b34d408390.png)

2020-09-02 15:01 UTC, ajluk commented on styles/designs/corn/pdf/_page-breaks.scss
> +}
@wilkus27 as we discussed I didn't understand your suggestion properly, but thank to this was able to notice I can make these selectors a little more general. :grinning:

2020-09-08 15:24 UTC, brittany-johnson commented on styles/designs/corn/pdf/_page-breaks.scss
> +.os-eoc.os-bring-together-exercises-container > section.bring-together-exercises > p {
Just curious if we need to have the class-specific selector for each one of these? For example: 
Instead of `.os-eos.os-section-exercises-container > section.section-exercises > p,` 
Will `.os-eos.os-section-exercises-container > section > p,` work?

2020-09-08 15:25 UTC, brittany-johnson approved these changes
Just had one question out of curiosity

2020-09-15 11:27 UTC, ajluk commented on styles/designs/corn/pdf/_page-breaks.scss
> +.os-eoc.os-bring-together-exercises-container > section.bring-together-exercises > p {
@brittany-johnson I was thinking about that as well, but it wouldn't reduce the amount of selectors, because we still need these sections specific selectors, so I have left them: 
![image](https://user-images.githubusercontent.com/55203598/93203800-4a5b4e00-f755-11ea-9e51-8bf370f77671.png)
But as you suggested it works without them (I have checked), so after your comment I have removed them.

2020-09-15 12:15 UTC, merged