issue-2629
openstax/cnx-recipes pull request #2723
Opened 2020-08-26 22:31 UTC by brittany-johnson

https://github.com/openstax/cnx-recipes/issues/2629

2020-08-27 21:40 UTC, brittany-johnson commented on styles/designs/common/pdf/_functions.scss
> -          display: table-cell,
Because removing this generated changes in all the books I believe we have two options: 
1. change the display to `optional` and add `display: table-cell` only where it is needed
2. visually check each place that is affected to ensure that there are no negative effects

2020-08-27 21:42 UTC, brittany-johnson commented on styles/designs/corn/parts/_exercises-components.scss
> -      display: enum('ValueSet:::REQUIRED'),
We'll have to check all of the places where the multi-column container is used in the corn theme to confirm that there are no negative effects.

2020-08-27 21:43 UTC, brittany-johnson commented on styles/designs/corn/parts/_exercises-components.scss
> +    display: enum('ValueSet:::OPTIONAL'),
If `table-cell` is required in some places we can add it via settings

2020-08-31 14:45 UTC, wilkus27 requested changes
@brittany-johnson I added some comments. Please let me know what do you think. If you think it is worth to try those ideas I can take care of it. Maybe in separate PR, in case something wouldn't work.

2020-08-31 14:45 UTC, wilkus27 commented on styles/designs/common/pdf/_functions.scss
> -          display: table-cell,
This function was created for Carnival theme, where text in columns goes from the top to the bottom. Maybe we shouldn't use it in Corn theme, instead we can create components with needed properties in corn files. What do you think?

2020-08-31 14:45 UTC, wilkus27 commented on styles/designs/corn/parts/_exercises-components.scss
> +      align-items: baseline,
I think we can remove this. I believe this property works only when component has also property `display: flex`.

2020-08-31 14:45 UTC, wilkus27 commented on styles/designs/corn/parts/_exercises-components.scss
> +        display: flex,
I'm wondering if it's necessery to use flexbox here. I think we can obtain the same effect when we just add `vertical-align: bottom` to `.os-problem-container`. At this moment we add this property only to problem containers with image/table on top. We didn't add this property everywhere because then exercises which start with paragraph containing math displayed in a wrong way. I checked and this problem also appears with changes from this PR:

![image](https://user-images.githubusercontent.com/40228854/91731712-78faf580-eba7-11ea-8424-91e9458af204.png)

(word "Solve" is not in line with exercise number). But if it's acceptable we can create just one component for problem container. It will have the same properties as `$Exercise__Problem__Container--WithImageTableOnTop`.

2020-09-01 12:12 UTC, wilkus27 commented on styles/designs/corn/parts/_exercises-components.scss
> +        display: flex,
I checked and `vertical-align: bottom` doesn't work as I expected. So it's better to stay with `display: flex` :wink:

2020-09-07 07:45 UTC, wilkus27 commented
@brittany-johnson I was trying to finish that and apply this solution also to Answer Key. Unfortunatelly, we can't do this :disappointed: The problem is in markup. In Eoc exercises we have:

```
section
  [data-type="exercise"]
    [data-type="problem"]
```
and `display: flex` is applied to exercise container. In Answer Key there is just:

```
section
  [data-type="solution"]
```
We can't apply flexbox to the whole section because Prince have problems with big elements with this property.

I tried to find another solution. Here is my PR https://github.com/openstax/cnx-recipes/pull/2751.

2020-09-08 15:38 UTC, brittany-johnson commented
> @brittany-johnson I was trying to finish that and apply this solution also to Answer Key. Unfortunatelly, we can't do this 😞 The problem is in markup. In Eoc exercises we have:
> 
> ```
> section
>   [data-type="exercise"]
>     [data-type="problem"]
> ```
> 
> and `display: flex` is applied to exercise container. In Answer Key there is just:
> 
> ```
> section
>   [data-type="solution"]
> ```
> 
> We can't apply flexbox to the whole section because Prince have problems with big elements with this property.
> 
> I tried to find another solution. Here is my PR #2751.

Okay, this is good to know. Thank you for testing this so thoroughly! I will close this PR now and review your new one!

2020-09-08 15:38 UTC, closed without merging