eoc solutions first elements
openstax/cnx-recipes pull request #2767
Opened 2020-09-14 14:54 UTC by ajluk

Issue: #2766

2020-09-14 18:59 UTC, Stackblocks approved these changes

2020-09-16 12:52 UTC, wilkus27 requested changes

2020-09-16 12:52 UTC, wilkus27 commented on recipes/mixins/_modify.scss
> +      }
Everything looks good :relaxed: I have one concern. This code is almost the same as part from the above. It differs only in a few places:

![image](https://user-images.githubusercontent.com/40228854/93339324-bad49e80-f82b-11ea-8371-f7116087d6a6.png)

Is it possible to reduce these parts to avoid repetition?

2020-09-16 12:52 UTC, wilkus27 commented on recipes/mixins/_modify.scss
> +    }
Same for this part :slightly_smiling_face:

2020-09-22 14:46 UTC, ajluk commented
For the problem with code refactoring in this PR will be opened a new issue card #2784

2020-09-22 15:00 UTC, wilkus27 approved these changes

2020-09-23 13:18 UTC, merged