restyle circled lists column width answer key eos exercises
openstax/cnx-recipes pull request #2798
Opened 2020-09-25 17:17 UTC by ajluk

Issues:  #2486, #2761

2020-09-29 12:36 UTC, wilkus27 requested changes
@Stackblocks @brittany-johnson I have a few questions to you. I'm not sure which approach will be better. I'm curious of your opinion :slightly_smiling_face:

2020-09-29 12:36 UTC, wilkus27 commented on styles/books/calculus/book.scss
> +
Edit: in direct conversation Ania explained me that problems with columns don't appear in dev-math books. That's why she decrease width only in calculus and precalculus books. Dev-math still has `33%`. @Stackblocks @brittany-johnson what do you think it will be better in this situation? To decrease width to `29%` everywhere for consistency (what requires more tests) or to apply different values depends on the books?

2020-09-29 12:36 UTC, wilkus27 commented on styles/designs/corn/parts/_lists-components.scss
> +        margin-right: enum('ValueSet:::REQUIRED'), //unused in EOC EOS exercises, Answer Key
Edit: @Stackblocks @brittany-johnson what do you think about it? It requires more work, because we have to check circled lists everywhere (in sections, notes etc.) Do you think it is worth spend more time to keep consistency? Or maybe we can merge it for now and apply these styles to all circled lists in another issue? What is your opinion?

2020-09-29 12:36 UTC, wilkus27 commented on styles/designs/corn/parts/_lists-components.scss
> +    display: enum('ValueSet:::OPTIONAL'), //unused in EOC EOS exercises, Answer Key
Here is the same problem. Some of the circled lists are styled differently. As Ania said, she resolved it in that way because issue is about lists in exercises from three column layout. @brittany-johnson @Stackblocks same question as in my previous comment. Should we style lists everywhere in the same way? If yes, should it be done in this PR or in another issue in the future?

2020-09-29 20:26 UTC, ajluk commented on styles/books/calculus/book.scss
> +
Yes, I have added changes only where it was necessary to save some time, because I thought we want to fix these issues sooner because of cardboard starting this week. I guess Natalia has already explained everything else. Thank you Natalia! :relaxed:

2020-10-07 14:58 UTC, brittany-johnson commented on styles/books/calculus/book.scss
> +
Hello! 
I think this is a good solution, but if there is a possibility of us having the issue in the other dev-math books it may be best to change them all to `29%`. 
I say this because I'm unsure if all of the final content is already in place in the other dev math books.

But if we have the issue in other dev math books we can always change it later. 
I'm fine with whatever you think is best : D

2020-10-07 15:18 UTC, brittany-johnson commented on styles/designs/corn/parts/_lists-components.scss
> +        margin-right: enum('ValueSet:::REQUIRED'), //unused in EOC EOS exercises, Answer Key
If we can use one value I think that would be best. I think whether we change it to a smaller consistent value or a smaller inconsistent value, we'll have to test everywhere. We don't have any pressing deadlines coming up so I think it would be fine to include these changes in this PR or another. Either is fine with me

2020-10-07 21:14 UTC, brittany-johnson requested changes
I left two responses, let me know what you think!

2020-10-09 17:12 UTC, ajluk commented on styles/books/calculus/book.scss
> +
Hi @wilkus27, @brittany-johnson I have decided to change the width to `29%` in all books exercises and answer keys with 3 column layout, because I have checked and noticed the same problem there. I also needed to do it because the separate list styling applied to them - float (I tried apply it everywhere, but it looks really bad in full page notes and examples, see the comments below) needs to decreased width to look good as well.

2020-10-09 17:22 UTC, ajluk commented on styles/designs/corn/parts/_lists-components.scss
> +    display: enum('ValueSet:::OPTIONAL'), //unused in EOC EOS exercises, Answer Key
@wilkus27 , @brittany-johnson I have tried to apply this styling everywhere, but it looks bad in examples and sometimes even notes as you can see below: 
![image](https://user-images.githubusercontent.com/55203598/95612382-9606cc00-0a63-11eb-9c26-31dc60bd40e8.png)
![image](https://user-images.githubusercontent.com/55203598/95612435-ab7bf600-0a63-11eb-90d0-8003b2d9730f.png)
So I have only applied it to lists in 3,2 column layout exercises and answer keys. Let me know if that's acceptable, I couldn't find any other solution for places like: 
![image](https://user-images.githubusercontent.com/55203598/95612753-30670f80-0a64-11eb-8ee0-68126906362d.png)
![image](https://user-images.githubusercontent.com/55203598/95612801-4248b280-0a64-11eb-84c2-a225f6173426.png)

How they look now:
![image](https://user-images.githubusercontent.com/55203598/95613080-abc8c100-0a64-11eb-92da-760c6f9e4d05.png)
![image](https://user-images.githubusercontent.com/55203598/95613059-a3708600-0a64-11eb-85b8-45d5ff4e3e4f.png)

2020-10-09 17:26 UTC, ajluk commented on styles/templates/template2/parts/_lists-settings.scss
> +));
I have created separate settings for lists in notes and examples to avoid overwriting them by settings applied to lists in exercises and solutions (answer key) for books with 3 column layout.

2020-10-09 17:30 UTC, ajluk commented on styles/templates/template2/parts/_lists-settings.scss
>  ));
I have also created separate settings for lists in eos, eoc exercises and answer key solutions, because they need to have separate selectors (to avoid overwriting in notes and examples) and using the same shape as them (ExercisesListsShape) .

2020-10-15 08:56 UTC, wilkus27 approved these changes
Everything looks good :relaxed: 

I have some ideas for the future how we can reorganize this to be more clear, but I think we can do this later, maybe during clean up. 

1. We can create two shapes: for lists in exercises from one column sections and from multicolumn sections. (Then for examples and notes we can use one selector `[data-type="page"] [data-type="problem"]` to cover both elements).
2. Since each book has different settings for the same sections (e.g. in Statistics EOC exercises are in one column) , we can define settings in `book.scss` file not in `lists-settings.scss`.
3. Maybe it will be more readable if we create separate components for lists from one column layout and multicolumn layout. Thats what we do for headers components. E.g there are components `H1`, `H1--Numbered`, `H3--LearningObjectives`. When component contains a lots of OPTIONAL or REQUIRED properties it is hard to understand how exactly this element is styled, and it's difficult to reuse it in other shapes (it's hard to find out what value should be applied in our case).

That's just my thoughts. @ajluk @brittany-johnson Let me know what is your opinion :) Do you think it is worth to create any issue for clean up?

2020-10-15 09:24 UTC, ajluk commented
@wilkus27 I think it' a good idea to clean it up a bit, but maybe we can do it later as a clean up issue, because these PRs are already old and there will be hard to resolve many conflicts, so it's better to merge it sooner. What do you think @brittany-johnson ?

2020-10-15 14:03 UTC, brittany-johnson approved these changes

2020-10-19 07:28 UTC, merged