Create basic files cardboard theme
openstax/cnx-recipes pull request #2802
Opened 2020-09-28 10:17 UTC by ajluk

Basic files for cardboard theme.

2020-09-28 10:19 UTC, ajluk commented on styles/books/business-ethics/book.scss
> +$bandColor: #1E7E91;
I have added the bands temporarily, because I haven't receive information from Larissa if we keep them in this theme as well.

2020-09-28 10:24 UTC, ajluk commented on styles/designs/cardboard/pdf/_folio.scss
> +    color: #000000;
I have created folio file for cardboard theme based on the carnival with only font and color changed based on the information from Larissa, but it could be changed later when we will get confirmation if this what is expected.

2020-09-28 13:56 UTC, Stackblocks approved these changes

2020-09-28 14:33 UTC, wilkus27 requested changes

2020-09-28 14:33 UTC, wilkus27 commented on books.txt
> +  "business-ethics            business-ethics                    914ac66e-e1ec-486d-8a9c-97b0f7a99774   col25722   easyvm5.cnx.org       mixins/                   template3"
Server should be changed to `katalyst01`

2020-09-28 14:33 UTC, wilkus27 commented on books.txt
> +  "business-ethics            business-ethics                    914ac66e-e1ec-486d-8a9c-97b0f7a99774   col25722   easyvm5.cnx.org       mixins/                   template3"
Please, check also if UUID and collection number is the same on katalyst

2020-09-29 06:45 UTC, wilkus27 approved these changes

2020-09-29 11:43 UTC, ajluk commented
I have updated the fonts and colors provided by Andy in the documentation issue.

2020-09-29 13:38 UTC, wilkus27 approved these changes

2020-09-30 11:03 UTC, merged