Create Additive Manufacturing
openstax/cnx-recipes pull request #2821
Opened 2020-10-01 15:16 UTC by Stackblocks

Issue Card: #2799 

To Do:
- [ ] Add to Books.txt
- [ ] Create Recipe Files
- [ ] Create Styles Files
- [ ] Polish to 80%
- [ ] Hook up to the dropdown, etc.

2020-10-02 16:12 UTC, brittany-johnson commented on books.txt
> +  "additive-manufacturing     additive-manufacturing             d7f23ac9-cf1c-498a-ae49-f34de2cb379f   col10000   content03.cnx.org     mixins/                   template2"
Since this is a new title, you'll have to also add it to the `RECIPE_DESC` above and re-generate the manifest

2020-10-20 10:12 UTC, wilkus27 requested changes

2020-10-20 10:12 UTC, wilkus27 commented on styles/books/additive-manufacturing/book.scss
> +@include use('KeyTerm','corn:::EocKeyTerm');
As I understand Additive Manufacturing contains different EOC sections then Statistics. There should be created styles for them. Also I think we can remove styles for sections which don't exists in Manufacturing.

2020-10-20 10:12 UTC, wilkus27 commented on styles/books/additive-manufacturing/book.scss
> +// Books using those settings: Introductory Statistics, Introductory Business Statistics, HS Statistics
This comment should be changed :wink:

2020-10-20 10:12 UTC, wilkus27 commented on books.txt
> +  "additive-manufacturing     additive-manufacturing             d7f23ac9-cf1c-498a-ae49-f34de2cb379f   col10000   content03.cnx.org     mixins/                   template2"
This is a side question :wink: Where this book will be tested? On content03 or katalyst01? As I understand content is not migreated to katalyst yet. Is it going to be added there?

2020-10-20 10:29 UTC, ajluk approved these changes

2020-10-20 14:53 UTC, Stackblocks commented on styles/books/additive-manufacturing/book.scss
> +@include use('KeyTerm','corn:::EocKeyTerm');
That's true! I just copied over the styles file whole-cloth so i'll clean it up to better match Additive Manufacturing.

2020-10-20 14:53 UTC, Stackblocks commented on books.txt
> +  "additive-manufacturing     additive-manufacturing             d7f23ac9-cf1c-498a-ae49-f34de2cb379f   col10000   content03.cnx.org     mixins/                   template2"
There isn't any _real_ data yet, there's 1.5 test chapters, but once there is a representative amount we can have it moved over to katalyst01 for testing.

2020-10-20 15:23 UTC, brittany-johnson commented
Starting to review now but wanted to link you to the symlink docs before I forgot. You'll have to follow the steps here so that the entry appears in the legacy dropdown. You'll also have to add the entry to the COPS dropdown which is 1000% simpler lol. I've linked to an example PR on how to do it. 

https://github.com/openstax/cnx/wiki/How-to-Create-a-Symlink-for-the-Legacy-Editor-Dropdown
https://github.com/openstax/output-producer-service/pull/146

2020-10-20 15:39 UTC, brittany-johnson commented
I agree w/ Natalia's comments. Once those are resolved then I think you'll be good!

2020-10-20 22:36 UTC, Stackblocks commented on styles/books/additive-manufacturing/book.scss
> +@include use('KeyTerm','corn:::EocKeyTerm');
Updated the style to remove the extra bits from Statistics and regenerated the output files. Please take a look and i'll merge tomorrow if everything is OK. Thanks!

2020-10-21 08:36 UTC, wilkus27 commented on styles/books/additive-manufacturing/book.scss
> +@include use('KeyTerm','corn:::EocKeyTerm');
@Stackblocks in my previous comment I was thinking about this sections from the issue description https://github.com/openstax/cnx-recipes/issues/2799

![image](https://user-images.githubusercontent.com/40228854/96694143-5c4d9380-1388-11eb-8e9c-5192b373dd3c.png)

There are no styles for them. But as you said, content is not ready, so if you feel it will be better to style them later when proper content be added I'm ok with that :wink:

2020-10-21 08:37 UTC, wilkus27 approved these changes
@Stackblocks I added one comment about EOC sections :slightly_smiling_face: Beside that everything looks good! :tada:

2020-10-23 14:53 UTC, Stackblocks commented
Per Larissa the new EoC pieces do not have bespoke styling, so i'll hook them up to the default for their type. ✅

2020-10-28 14:29 UTC, merged