style blockquotes business ethics
openstax/cnx-recipes pull request #2823
Opened 2020-10-01 15:26 UTC by ajluk

Issue:  #2822

2020-10-01 18:22 UTC, Stackblocks requested changes
Looks good aside from some spare newlines here and there :+1:

2020-10-01 18:22 UTC, Stackblocks commented on styles/books/business-ethics/book.scss
> +
Any reason for the added line here?

2020-10-01 18:22 UTC, Stackblocks commented on styles/templates/template3/_design.scss
> +
If this is a gap for the purposes of separation could you include a comment about what differentiates the groups?

2020-10-01 18:22 UTC, Stackblocks commented on styles/templates/template3/_settings.scss
> +
Extra spacing here as well

2020-10-02 07:36 UTC, wilkus27 requested changes

2020-10-02 07:36 UTC, wilkus27 commented on styles/output/business-ethics-pdf.css
> +  margin-right: 0.25inch; }
Somethings went wrong :thinking: Settings are added to the root not to blockquote.

2020-10-02 15:51 UTC, ajluk commented on styles/books/business-ethics/book.scss
> +
I think I have pasted the settings first here by accident and left the line empty after removing it. Thanks!

2020-10-02 15:55 UTC, ajluk commented on styles/templates/template3/_design.scss
> +
Yes, I just wanted to separate the shapes that are inside the `parts` folder from the others,  common/pdf shapes as we did for the previous themes.

2020-10-02 15:57 UTC, ajluk commented on styles/output/business-ethics-pdf.css
> +  margin-right: 0.25inch; }
@wilkus Thank you for catching it up!

2020-10-05 14:42 UTC, Stackblocks approved these changes

2020-10-06 08:10 UTC, wilkus27 approved these changes

2020-10-06 09:34 UTC, merged