style footnotes business ethics
openstax/cnx-recipes pull request #2830
Opened 2020-10-02 12:54 UTC by ajluk

Issue: #2824

2020-10-02 15:29 UTC, ajluk commented
The link color will be added within this PR: https://github.com/openstax/cnx-recipes/pull/2823. I will update my branch then.

2020-10-07 08:51 UTC, wilkus27 requested changes

2020-10-07 08:51 UTC, wilkus27 commented on recipes/books/_generator.scss
> +    }
I would recommend to enable `move-footnotes` flag for Business Ethics. Then this part of code shouldn't be changed.

2020-10-07 08:51 UTC, wilkus27 commented on recipes/mixins/_count.scss
> +    '[data-type="chapter"], .appendix',
Is this change necessary?

2020-10-07 08:51 UTC, wilkus27 commented on recipes/mixins/_number.scss
> +
I think we should have just one config for custom footnotes. It was already created for footnotes in precalc, but I just noticed that we didn't modify it after tags for footnotes changed, so it doesn't work now and footnotes in precalc are not numbered properly :disappointed: 

In this situation, I think we should keep all mixins created by you in this PR and I will create separate issue for footnotes in Precalc. Then some of us will modify your mixins to add additional option needed in this book and remove old mixins. What do you think?

2020-10-07 12:26 UTC, ajluk commented on recipes/mixins/_count.scss
> +    '[data-type="chapter"], .appendix',
No, I have just left it accidentally. Already removed! :)

2020-10-07 12:27 UTC, ajluk commented on recipes/mixins/_number.scss
> +
Yes, it's a good idea. These changes could be rather time consuming.

2020-10-09 08:11 UTC, wilkus27 approved these changes

2020-10-09 16:49 UTC, Stackblocks approved these changes

2020-10-12 10:18 UTC, merged