Chapter intro business ethics
openstax/cnx-recipes pull request #2859
Opened 2020-10-11 12:55 UTC by ajluk

Issue: #2851

2020-10-20 21:52 UTC, Stackblocks approved these changes

2020-10-21 09:19 UTC, wilkus27 requested changes

2020-10-21 09:19 UTC, wilkus27 commented on styles/designs/cardboard/parts/_titles-components.scss
> +    margin-top: enum('ValueSet:::OPTIONAL'), //used in Chapters
There is so many OPTIONALs here. Based on the our work on previous themes I have a feeling it's very confusing. When we want to reuse some component later it's very hard to find out which property should be used in our case. What do you think to create separate components if we need to change a lot of properties? In this case I would create `H1--ChapterIntro`, `H1--ChapterIntro__Text` etc. and apply as much hard coded values as possible. It's just my point of view. :wink:   I'm really curious what is your opinion. Maybe you like more to have less amount of components which contain REQUIRED and OPTIONAL properties. Let me know what do you think :slightly_smiling_face:

2020-10-21 09:19 UTC, wilkus27 commented on styles/designs/cardboard/parts/_chapterintro-components.scss
> +        font-size: enum('ValueSet:::REQUIRED'),
Can we hard code it?

2020-10-21 09:54 UTC, ajluk commented on styles/designs/cardboard/parts/_titles-components.scss
> +    margin-top: enum('ValueSet:::OPTIONAL'), //used in Chapters
Yes, it is a good idea to create new component for such cases. :slightly_smiling_face:

2020-10-23 16:03 UTC, wilkus27 requested changes

2020-10-26 14:58 UTC, wilkus27 approved these changes
Everything looks good! :relaxed: A lot of work is done here. Good job! :+1:

2020-10-27 10:16 UTC, merged