style no class tables business law
openstax/cnx-recipes pull request #2891
Opened 2020-10-23 15:37 UTC by ajluk

Issue: #2890

2020-10-23 16:27 UTC, ajluk commented on styles/templates/template3/parts/_table-settings.scss
> +        ),
I have just added different selector and settings for these tables and they will be using the same shapoe as Fake Title Tables, because the only difference is that they don't have the title present in the FakeTitleTable shape. But let me know if these tables should rather have separate shape, because the markup is a little different.

2020-10-26 16:10 UTC, wilkus27 requested changes

2020-10-26 16:10 UTC, wilkus27 commented on styles/templates/template3/parts/_table-settings.scss
> +        ),
Hmm :thinking: Based on the specs from https://github.com/openstax/cnx-recipes/issues/2741 there are actually two types of tables: with and without borders. So maybe we can name shapes based on this property? For example `TablesWithBordersShape` and `TablesWithoutBordersShape`. Then `top-titled` tables and `no class` tables will use the first one and `text-heavy` tables the second one. What do you think? cc @Stackblocks

2020-10-26 18:28 UTC, Stackblocks commented on styles/templates/template3/parts/_table-settings.scss
> +        ),
I like that. It's descriptive of the specific use-cases and doesn't lose too much versatility since all of the tables fall into one of those two groups anyways. ✅

2020-10-26 18:28 UTC, Stackblocks approved these changes

2020-10-27 08:33 UTC, ajluk commented on styles/templates/template3/parts/_table-settings.scss
> +        ),
Yes. That's a good idea! :smile:

2020-10-28 09:30 UTC, wilkus27 approved these changes

2020-10-29 13:51 UTC, brittweinstein commented
@ajluk we can merge

2020-11-02 08:10 UTC, merged