Update styles + recipes docs
openstax/cnx-recipes pull request #2911
Opened 2020-10-27 21:21 UTC by brittany-johnson

2020-10-28 20:59 UTC, Stackblocks commented
![image](https://user-images.githubusercontent.com/12678235/97496126-811caa80-1936-11eb-91e9-b72a17cb95aa.png)

Starting in on this review but it'll take a bit 👍

2020-10-29 10:00 UTC, ajluk reviewed
@brittany-johnson I have noticed that after creating the directory for `desing-settings/<theme name>` you have also left the previous directory `templates/tamplate1-3/`. Was it intentional?

2020-10-30 16:29 UTC, wilkus27 commented on styles/output/anatomy-rex-web.css.map
> +		"../build/../design-settings/carnival/_design.scss",
Do we still need those files with `rex-web`?

![image](https://user-images.githubusercontent.com/40228854/97731224-28cfdf00-1ad5-11eb-8f13-8adbff6bbd4a.png)

Only books from carnival theme have them. I don't remember what is the reason that they are not generated in corn and cardboard :thinking:

2020-10-30 16:46 UTC, wilkus27 requested changes
Wow :open_mouth: A lot of work is done here. I left only two comments. Beside that everything looks good :relaxed:

2020-10-30 16:46 UTC, wilkus27 commented on styles/templates/template1/_settings.scss
> -@import 'templates/template1/parts/unit-settings.scss';
I think all files starts from this one to the end should be removed. They are in old directory

![image](https://user-images.githubusercontent.com/40228854/97732715-3c7c4500-1ad7-11eb-9e46-c0b2184ede76.png)

I'm not sure if this is what @ajluk meant in her comment, so I leave this note also here.

2020-10-30 19:56 UTC, ajluk commented on styles/templates/template1/_settings.scss
> -@import 'templates/template1/parts/unit-settings.scss';
Yes, this is what I had in mind.  :+1:

2020-11-06 20:24 UTC, Stackblocks approved these changes

2020-11-11 16:56 UTC, brittany-johnson commented on styles/output/anatomy-rex-web.css.map
> +		"../build/../design-settings/carnival/_design.scss",
Good question! At the beginning of the baked styles project, we intended on serving styles to REX, but that portion of the work was delayed. We'll be picking up on this again next year though.

2020-11-12 16:31 UTC, Stackblocks requested changes
A couple of editorial changes requested but otherwise looking good!

2020-11-12 16:31 UTC, Stackblocks commented on books.txt
> +  "algebra-trigonometry       precalculus                        13ac107a-f15f-49d2-97e8-60ab2e3b519c   col11758   katalyst01.cnx.org    mixins/                   corn"
Sorry to make you interact with this more, but would you please adjust these two so they maintain alphabetical order?

2020-11-12 16:31 UTC, Stackblocks commented on styles/README.md
> +### Writing the componenets and shapes
typo on "components" throughout

2020-11-12 16:31 UTC, Stackblocks commented on recipes/css-extensions.md
> +
Please condense extra whitespace

2020-11-12 17:10 UTC, ajluk approved these changes

2020-11-12 18:04 UTC, kswanson33 requested changes
Sneaking in a few technically-outside-the-PR change requests:

- styles/README.md line 158: current line reads 'map-merge($boxed_note_container, (`, change to `map-merge($Note--Boxed__Container, (`
- styles/README.md line 211: current line reads `import 'design/example/design';`, change to `import 'designs/example/design';`

2020-11-13 18:55 UTC, merged