style exploring business careers note intro business
openstax/cnx-recipes pull request #2922
Opened 2020-10-29 11:29 UTC by ajluk

Issue: #2921

2020-10-29 11:33 UTC, ajluk commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-left-color: enum('ValueSet:::OPTIONAL'), //udes only in Option 4
In Option 4 there are borders present around the `body` and `title`and I have set them to `OPTIONAL`, because they aren't needed for the rest of the note options, but they are using the same shape. Let me know if creating a separate shape and body/title components in this case will be a better solution.

2020-10-29 11:35 UTC, ajluk commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        box-decoration-break: slice,
I have also added this property which is necessary for notes with borders. It doesn't change the look for notes they don't have the borders, so it can be hardcoded.

2020-10-29 14:50 UTC, wilkus27 requested changes

2020-10-29 14:50 UTC, wilkus27 commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-left-color: enum('ValueSet:::OPTIONAL'), //udes only in Option 4
Hmm I would vote for a new components and new shape. For example `$Notes--Boxed__Title--WithBorders` or something like that. I think it will be more clear.

2020-10-29 14:59 UTC, Stackblocks commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-left-color: enum('ValueSet:::OPTIONAL'), //udes only in Option 4
Also, as a very minor thing, the "udes" in the Option 4 comment is a typo

2020-10-29 15:00 UTC, Stackblocks approved these changes

2020-10-30 21:01 UTC, ajluk commented
@brittany-johnson I have added you to this review as a second reviewer, because Natalia is on vacation since Monday and there were some requested changes from her here, could you take a look?

2020-11-04 20:03 UTC, brittany-johnson requested changes

2020-11-05 09:47 UTC, ajluk commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-top-left-radius: 0.25rem,
@brittany-johnson I have tried that solution but it is the same issue as with border and padding shorthand property as I exepected, that's the reason I'm avoiding them. When we set four borders/paddings values in one property they ignore the three of them as you can see on the screenshot below. The `border-radius` property value has been reduced from `0.25rem 0.25rem 0rem 0rem` to 0.25 rem` to 0.25rem for all of the borders: 
![image](https://user-images.githubusercontent.com/55203598/98224765-2c8bb780-1f54-11eb-9cca-d06d5ffb7339.png)

2020-11-05 16:49 UTC, Stackblocks approved these changes

2020-11-05 16:49 UTC, Stackblocks commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-top-left-radius: 0.25rem,
I can't find anything in the sass documentation about it simplifying border/margins or requiring specific syntax for the shorthand version, so I wonder why this is happening...

I'm with Brittany J in that _ideally_ these would be compressed for simplicity's sake, but if the framework is fighting against it we may want to move forward with the expanded version for the time being.

2020-11-05 19:27 UTC, brittany-johnson requested changes

2020-11-05 19:27 UTC, brittany-johnson commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-top-left-radius: 0.25rem,
I think it should work if we put the value in quotes. 
I also just tested without, and it condensed the value to just `0.25rem`, so strange! I don't have an explanation as to why that happens 😂

![Screen Shot 2020-11-05 at 1 25 45 PM](https://user-images.githubusercontent.com/24909007/98287058-741d3e00-1f6a-11eb-8ad8-320814ed229e.png)
![Screen Shot 2020-11-05 at 1 25 51 PM](https://user-images.githubusercontent.com/24909007/98287061-754e6b00-1f6a-11eb-9895-13ca84cad92c.png)

2020-11-06 10:27 UTC, ajluk commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        border-top-left-radius: 0.25rem,
@brittany-johnson Thank you! :heart_eyes:  I also don't know why without quotes the shorthand property is not working.

2020-11-06 15:37 UTC, brittany-johnson approved these changes

2020-11-06 21:22 UTC, Stackblocks approved these changes

2020-11-12 11:16 UTC, merged