add principles management to template
openstax/cnx-recipes pull request #3049
Opened 2020-11-12 12:39 UTC by ajluk

This Pr only adds Principles of management to template.

2020-11-17 14:01 UTC, ajluk commented on styles/books/pl-u-physics/book.scss
@brittany-johnson I have updated the branch with `new-x.x` just to check if it resolve the problem with not passing checks and there were some paths that needed to be fixed after your changes, so I have done it within this PR.

2020-11-17 16:56 UTC, Stackblocks approved these changes

2020-11-19 16:00 UTC, brittany-johnson requested changes
Just have one comment, other than that this is a great solution, good job!

2020-11-19 16:00 UTC, brittany-johnson commented on styles/output/intr-business-pdf.css
> +@charset "UTF-8";
I noticed that two of the files for intro-business are spelled `intr-business`

2020-11-19 16:18 UTC, ajluk commented on styles/output/intr-business-pdf.css
> +@charset "UTF-8";
Thank you for noticing! I missed it somehow.

2020-11-19 19:37 UTC, brittany-johnson approved these changes
Yay!!

2020-11-19 20:10 UTC, Stackblocks approved these changes

2020-11-20 08:05 UTC, merged