implement styling for concepts-practice elements
openstax/cnx-recipes pull request #3060
Opened 2020-11-16 21:07 UTC by kswanson33

Issue #2943 

![image](https://user-images.githubusercontent.com/26280712/99306833-b7f22c00-2823-11eb-8801-b6a1496ffa30.png)

2020-11-16 21:10 UTC, kswanson33 commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        letter-spacing: 3px,
I should point out that I used a static value here, rather than something like letter-spacing(1). Is there a better way of doing this?

2020-11-16 22:00 UTC, kswanson33 commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        letter-spacing: 3px,
I think this is causing the build to fail as well!

2020-11-17 14:42 UTC, brittany-johnson approved these changes
Left a couple of comments, otherwise, looking great!

2020-11-17 14:42 UTC, brittany-johnson commented on styles/designs/cardboard/parts/notes/_notes-components.scss
> +        letter-spacing: 3px,
Yes, it looks like the build is failing due because px is being used instead of rem. 

I forgot to mention before that we have a `_grid.scss` file where we keep functions used for spacing. The most frequently used ones are probably `v-spacing` for vertical spacing and `h-spacing` for horizontal. 
We try to use the functions for spacing whenever possible. If a value needs to be super specific, like -5.654rem (or something like that), then its fine to go off the grid since the current functions won't return that value

cc: @LostMojo

2020-11-17 14:42 UTC, brittany-johnson commented on styles/books/accounting/book.scss
> +        Title: (
When writing settings in the `book.scss` file we historically opt for the 'one-line' style to save space and make it easier to read. For example, `Title` would be written like this: 

`'Title:::color': (_ref: "colorMap:::noteOption2HeaderColor"),`

Also, be sure to use the color map for colors. 

cc: @LostMojo

2020-11-17 14:42 UTC, brittany-johnson requested changes
Oops didn't mean to approve lol

2020-11-17 20:04 UTC, brittany-johnson approved these changes
Woo!!!

2020-11-17 22:45 UTC, Stackblocks approved these changes

2020-11-18 15:20 UTC, merged