Style YourTurn Boxed Note
openstax/cnx-recipes pull request #3070
Opened 2020-11-18 20:14 UTC by LostMojo

#2944 

<img width="775" alt="Screen Shot 2020-11-16 at 3 09 48 PM" src="https://user-images.githubusercontent.com/5740972/99582822-42639880-29a8-11eb-8f73-8df8d68e6b5b.png">

2020-11-18 22:23 UTC, Stackblocks approved these changes

2020-11-19 19:19 UTC, kswanson33 approved these changes

2020-11-19 19:35 UTC, brittany-johnson requested changes

2020-11-19 19:35 UTC, brittany-johnson commented on styles/books/accounting/book.scss
> +        'Title:::letter-spacing': .3rem,
I don't see this letter-spacing value used in business-ethics for note option 3. Is this value necessary to the design?

2020-11-19 19:58 UTC, LostMojo commented on styles/books/accounting/book.scss
> +        'Title:::letter-spacing': .3rem,
Oh! No it isn't. Let me fix that

2020-11-19 20:08 UTC, brittany-johnson approved these changes

2020-11-19 20:10 UTC, merged