Implement colored text emphasis in R1 for accounting
openstax/cnx-recipes pull request #3072
Opened 2020-11-19 18:01 UTC by kswanson33

#2892 
![image](https://user-images.githubusercontent.com/26280712/99705012-2a9f1980-2a67-11eb-8e8e-28befa8fbb3e.png)

2020-11-19 18:03 UTC, kswanson33 commented on styles/design-settings/cardboard/_colors.scss
> +    emTextColor: (_ref: "scheme:::R1"),
Is this a good name for this color?

2020-11-19 18:03 UTC, kswanson33 commented on styles/designs/cardboard/parts/_emtext-components.scss
> +$ColoredText__Container: (
Is it appropriate to create a new component & shape for emphasizing text, or is there an existing shape & component file that I could add these changes to instead?

2020-11-19 20:21 UTC, LostMojo commented on styles/design-settings/cardboard/_colors.scss
> +    emTextColor: (_ref: "scheme:::R1"),
It seems to match the naming conventions in the other styles-- Carnival's reds are also named in the R1, R2 pattern.

2020-11-19 20:30 UTC, LostMojo commented on styles/design-settings/cardboard/_colors.scss
> +    emTextColor: (_ref: "scheme:::R1"),
Oh!! But should we spell out Emphasis? The map names seem to weigh clarity over briefness, so it might be worth it to spell things out.

2020-11-19 20:45 UTC, LostMojo requested changes
It looks good to me! However, I do think it would be worth it to refactor EmText to something a little more descriptive & specific. "Em" isn't immediately apparent, and the shape is being applied to text that's emphasized _and_ colored.

2020-11-19 20:45 UTC, LostMojo commented on styles/books/accounting/book.scss
> +    EmText: (
I think EmText could be a little more clear about its purpose. It might be worth refactoring it to something like "EmphasizedText" or even "EmphasizedColoredText"?

2020-11-19 22:45 UTC, brittany-johnson commented on styles/designs/cardboard/parts/_emtext-components.scss
> +$ColoredText__Container: (
Good question! I think the best place to put it now would be in `common-components` and include it in the book root shape since this `colored-text` class could be anywhere from my understanding

2020-11-19 22:46 UTC, brittany-johnson commented on styles/books/accounting/book.scss
> +    EmText: (
Yes I agree! EmphasizedColoredText would be a good name

2020-11-19 22:47 UTC, brittany-johnson requested changes
Left a comment ~

2020-11-20 17:52 UTC, kswanson33 commented on styles/books/accounting/book.scss
> +    EmText: (
Resolved!

2020-11-20 17:52 UTC, kswanson33 commented on styles/designs/cardboard/parts/_emtext-components.scss
> +$ColoredText__Container: (
Resolved!

2020-11-30 15:12 UTC, LostMojo approved these changes

2020-12-01 14:46 UTC, brittany-johnson approved these changes
Looks good!

2020-12-01 17:07 UTC, merged