Fixes the cardboard ToC by adding missing styles; implements ToC for Accounting
openstax/cnx-recipes pull request #3075
Opened 2020-11-20 20:49 UTC by kswanson33

#2934 #2897 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/26280712/99848309-8b058800-2b47-11eb-8362-062b6e83c2af.png">

(will ultimately be merged into the next milestone)

2020-11-30 19:29 UTC, LostMojo approved these changes
Looks good!

2020-11-30 19:29 UTC, LostMojo commented on styles/designs/cardboard/parts/_toc-components.scss
> +  _subselector: ' > li.os-toc-chapter:nth-child(2n)',
Does this still select the odd items? It looks like it's the even items that have backgrounds.

2020-11-30 19:35 UTC, kswanson33 commented on styles/designs/cardboard/parts/_toc-components.scss
> +  _subselector: ' > li.os-toc-chapter:nth-child(2n)',
Counterintuitively, yes -- since the first item in this list (in all books I looked at) is the preface, odd numbered chapters are actually even list items. 

But this is a good issue to raise: if a book doesn't have a preface, the above will stop working. Is this something to worry about?

2020-12-01 14:41 UTC, brittany-johnson requested changes
I haven't looked at your code yet but I noticed in the screenshot that the page numbering is now off in the TOC. [Here is a PDF on production for reference ](https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/FinancialAccounting-OP_YioY6nY.pdf)

The text is also very close to the right border of the darker gray background. 

Let me know if you have any questions!

2020-12-02 20:43 UTC, kswanson33 commented
![image](https://user-images.githubusercontent.com/26280712/100928910-db200b00-34b4-11eb-84e1-66ebb12d692d.png)

Addresses the padding issue so that padding resembles the PDF on prod. Specs added to Top Level List Item:
- `padding-top: v-spacing(2),`
- `padding-bottom: v-spacing(2),`
- `padding-right: h-spacing(5),`
- `padding-left: h-spacing(1),`

2020-12-03 16:04 UTC, kswanson33 commented
![image](https://user-images.githubusercontent.com/26280712/101053716-1de5ef80-3556-11eb-8f40-94edc1ed20ec.png)

For the page numbering to start at page 1 for the Preface, `class="preface"` must be added to the page containing the preface. (Sample image is from me making this change locally -- the problem still needs to be fixed for the baked XHTML.)

2020-12-03 22:06 UTC, kswanson33 commented
![image](https://user-images.githubusercontent.com/26280712/101094100-df6a2800-3589-11eb-98e9-c762f454b4de.png)

ToC for intro-business

2020-12-07 17:37 UTC, Stackblocks approved these changes

2020-12-07 19:48 UTC, merged