adds Think It Through Styling
openstax/cnx-recipes pull request #3112
Opened 2020-12-01 17:48 UTC by LostMojo

#2942 
<img width="1178" alt="Screen Shot 2020-12-01 at 11 42 08 AM" src="https://user-images.githubusercontent.com/5740972/100776743-8738f780-33ca-11eb-93af-ef7bd1cdaedf.png">

2020-12-01 20:51 UTC, kswanson33 approved these changes
Left a few thoughts, but looks good overall!

2020-12-01 20:51 UTC, kswanson33 commented on styles/books/accounting/book.scss
> +        "Subtitle:::font-family": ( _ref: "typography:::titleFont" ),
Same thought as in code review yesterday -- could the ThinkItThrough and ConceptsPractice become one settings block, with a comment to indicate what types of note they affect? Looks like they use the same settings.

2020-12-01 20:51 UTC, kswanson33 commented on styles/books/accounting/book.scss
> +@include use('ThinkItThrough', 'cardboard:::BoxedNoteWithSubtitleShape');
This isn't in the scope of this card, but I happened to notice yesterday in code review that other books import `@include use('NotesLists', 'cardboard:::NotesListsShape');`. This import seems to align list items correctly within the note box (there's a couple of Your Turn notes in chapter 3 with lists). Since I don't think there's specifically a card for that import, I thought this might be a good PR to sneak that in!

2020-12-02 08:12 UTC, ajluk commented on styles/books/accounting/book.scss
> +@include use('ThinkItThrough', 'cardboard:::BoxedNoteWithSubtitleShape');
@kswanson33 Yes, you're right. We have created separate shape for lists that are placed in notes, so it's a good practice to include this shape whenever there are lists present within a note that someone is working on and there some additional changes needed for the lists inside note we're adding it there as well.

2020-12-02 08:16 UTC, ajluk commented on styles/books/accounting/book.scss
> +        "Subtitle:::font-family": ( _ref: "typography:::titleFont" ),
@kswanson33 It is a good thought, but the notes have different selectors and if we include two or more selectors together in one settings it cause problems sometimes with creating next selectors within a shape, that's why we're adding them separately.

2020-12-02 08:19 UTC, ajluk requested changes
@LostMojo Everything looks good, but could you include the Note Lists Shape within this PR, because notes that have lists inside are already styled and I'm afraid it can be missed later?

2020-12-02 17:44 UTC, ajluk approved these changes

2020-12-03 20:28 UTC, merged