style accounting notes
openstax/cnx-recipes pull request #3119
Opened 2020-12-03 21:56 UTC by kswanson33

#2946 #2948 #2947 #2945

![image](https://user-images.githubusercontent.com/26280712/101092663-fd368d80-3587-11eb-8025-e70d4e605a03.png)

![image](https://user-images.githubusercontent.com/26280712/101092712-10e1f400-3588-11eb-8f8f-f7ac8767585a.png)

![image](https://user-images.githubusercontent.com/26280712/101093098-4ab2fa80-3588-11eb-80c8-4ae822a41247.png)

![image](https://user-images.githubusercontent.com/26280712/101093196-6ae2b980-3588-11eb-9ae6-1f21a137518c.png)

2020-12-04 17:37 UTC, ajluk reviewed
Everything looks good! I have just left a comment about changing the note naming convention and I'm curious what the rest of the team think about it.

2020-12-04 17:37 UTC, ajluk commented on styles/books/accounting/book.scss
> +    Opt3Note: (
@kswanson33 The idea to use the number of styling option from the specs in the note name is really good! But if we would like to change the naming convention for the notes, all of the notes names should be changed as well for other books. There are also some notes with icon in this theme, so then the name could be `Opt3WithIcon` for example. @brittany-johnson @wilkus27 @Stackblocks @LostMojo what do you thin of this idea?

2020-12-04 17:51 UTC, ajluk commented on styles/books/accounting/book.scss
> +    Opt3Note: (
I'm only concerned what the name should look like in the case when more that one note uses the same option styling number (like in Principles of Management). Maybe we could use both note and option name f.ex: `YourTurnOpt3`.

2020-12-04 21:38 UTC, LostMojo commented on styles/books/accounting/book.scss
> +    Opt3Note: (
Well, if we're hoping to make this an overarching style goal, it would be good to have specific categories (like Opt3NoteWithIcon) but making the name more specific (like YourTurnOpt3) would undermine making the categories broadly applicable.

2020-12-04 23:05 UTC, Stackblocks commented on styles/books/accounting/book.scss
> +    Opt3Note: (
The overlap of more than one note using the styling number can be helped out by having comments listing the notes that use the option above each one, like 

```
//Used in: Your Turn, Note B, Note C
NoteOption3Icon
...
```

Like Mary Jo said, we don't want to introduce new points that require unique code chunks.

This may be something to set out in a separate card like converting everything to BEM was, just so the fixes in this card aren't held up.

2020-12-07 11:28 UTC, ajluk commented on styles/books/accounting/book.scss
> +    Opt3Note: (
@Stackblocks I meant that when there will be more than one note using the same styling option in the same book, the name used in the settings for these notes will be the same, but the notes have different selectors so the name must be different too for each one of them. It can be mixed with note title and styling option like I and MaryJo have written above f.ex.:`YourTurnOpt3`. If we decide the change the naming convention for the notes in cardboard I guess MaryJo can create a card to change it in every book in the future during the cleaning.

2020-12-07 13:21 UTC, wilkus27 requested changes

2020-12-07 13:21 UTC, wilkus27 commented on styles/books/accounting/book.scss
> +    Opt3Note: (
First I was very enthusiastic with conception that @kswanson33 applied. It avoids a lots of repetitions. But after discusion with @ajluk I'm not sure if it's a good idea. As Anna noticed, in some books we style notes with some option but they have additional icon, different for each note (each selector). In this case we have to create separate settings. Here is the example: https://github.com/openstax/cnx-recipes/issues/2737#issuecomment-730379256. In this case, in my opinion, it will be better to use old conception for consistency, even there are repetitions. It might be confusing in  the future why some notes use `Opt3Note` settings and another self named settings even they are styled like notes from Option 3.

2020-12-07 16:11 UTC, Stackblocks commented
For the time being we should move forward with the old-style to get this card moving again, and we can include the ideas being discussed here in the to-do list for problems to work out as we continue improving our code base and pipelines.

2020-12-07 17:11 UTC, kswanson33 commented
Sounds good. Thanks for all the input!

2020-12-08 16:17 UTC, wilkus27 requested changes

2020-12-08 16:17 UTC, wilkus27 commented on styles/books/accounting/book.scss
> +        _selectors: ('.concepts-practice', '.ifrs-connection', '.continuing-application', '.ethical-considerations'),
There should be only selector for Concept Practice note. Same for notes from below :wink:

2020-12-08 16:17 UTC, wilkus27 commented on styles/books/accounting/book.scss
> +    IFRS: (
We are using Camel Case for naming. So it should be `Ifrs`. I would also reccomend to name it similar to note class, so maybe `IfrsConnection`.

2020-12-08 16:46 UTC, wilkus27 approved these changes

2020-12-09 14:57 UTC, Stackblocks approved these changes

2020-12-09 16:52 UTC, merged