Style eoc exercises
openstax/cnx-recipes pull request #3144
Opened 2020-12-08 21:33 UTC by kswanson33

#2893

2020-12-10 21:47 UTC, LostMojo approved these changes

2020-12-11 13:34 UTC, ajluk requested changes

2020-12-11 13:34 UTC, ajluk commented on styles/designs/cardboard/parts/_exercises-components.scss
> +    color: enum('ValueSet:::REQUIRED'),
@kswanson33 The name for the `$Exercise__ProblemSolution__Text` component should be changed to `ProblemSolutionNumberText` f.ex. Now it has the same name as the components below. Color property value should be set for it in the book.scss file as well. I have also noticed the you haven't regenerate all the styles for all books. Some other books are using this shape as well, so there the change should be also visible and color for this component should be set in their book.scss files as well. Maybe a better solution could be to create a separate shape for exercises for Accounting book with this additional component, what do you think? Let me know what is you opinion @Stackblocks @LostMojo ?

2020-12-11 15:27 UTC, Stackblocks commented on styles/designs/cardboard/parts/_exercises-components.scss
> +    color: enum('ValueSet:::REQUIRED'),
Yeah, the `_name` needs to be changed so there isn't a collision between `$Exercise__ProblemSolution__Text` and `$Exercise__ProblemSolution__Number`.

As for the colors, if there's going to be any variance when reusing a component we should use `enum'ValueSet:::REQUIRED'` in the shape if the setting has to be present, or `enum'ValueSet:::OPTIONAL'` if the setting can be present in some iterations but not all of them; and then put the actual specific setting in the most specific place it can be. We want to build as few new shapes as possible, but as many as is necessary.

Additionally, Anna is right about regenerating all of the styles before pushing your final changes to GitHub and it is a good habit to get into when working with shapes so you can get a flag if something you've changed has had unexpected impacts in other books. (It also keeps Travis from throwing a fit) The same is true of Recipes when you start working on those.

2020-12-11 16:32 UTC, kswanson33 commented on styles/designs/cardboard/parts/_exercises-components.scss
> +    color: enum('ValueSet:::REQUIRED'),
Thank you for catching this! To me, setting the enum value to OPTIONAL seems like the best solution here. Thoughts?

2020-12-11 17:55 UTC, ajluk commented on styles/designs/cardboard/parts/_exercises-components.scss
> +    color: enum('ValueSet:::REQUIRED'),
Sure, if we prefer less shapes than less properties Alan proposition would be the best and fastest choice :)  
Although in this case not only the color doesn't appear in the feature but the whole component. Alan if we can accept that approach I'm ok with it as well.

2020-12-11 17:56 UTC, ajluk approved these changes

2020-12-11 18:40 UTC, ajluk reviewed
I have just left a comment to confirm we're on the same page :relaxed:

2020-12-11 21:19 UTC, merged