fix endnotes styling
openstax/cnx-recipes pull request #3156
Opened 2020-12-10 12:48 UTC by ajluk

Issue:  #3045

2020-12-11 15:33 UTC, Stackblocks requested changes

2020-12-11 15:33 UTC, Stackblocks commented on styles/designs/cardboard/parts/_eoc-components.scss
> +    _name: "EndnoteNoteSection",
This is the only one with `EndnoteNote...` is that intentional?

2020-12-14 13:53 UTC, ajluk commented on styles/designs/cardboard/parts/_eoc-components.scss
> +    _name: "EndnoteNoteSection",
@Stackblocks It's a typo. Thank you for catching it up!

2020-12-14 15:15 UTC, kswanson33 approved these changes

2020-12-14 20:11 UTC, Stackblocks approved these changes

2020-12-15 12:04 UTC, merged