Issue 2888 chapter outline introduction
openstax/cnx-recipes pull request #3159
Opened 2020-12-10 16:31 UTC by LostMojo

Styles the Chapter Outline for #2888 with some overlap with #2655 . (If you bake it, make sure you're looking at the pdf, styling will not work in a browser)

<img width="851" alt="Screen Shot 2020-12-10 at 10 19 40 AM" src="https://user-images.githubusercontent.com/5740972/101798992-3d8a9400-3ad1-11eb-81e9-a661f87115a7.png">

2020-12-10 20:26 UTC, LostMojo commented
The lack of border broke during merging, taking it back to fix

<img width="838" alt="Screen Shot 2020-12-10 at 2 08 07 PM" src="https://user-images.githubusercontent.com/5740972/101825763-b3075c00-3af3-11eb-9104-6b92047c5b55.png">

2020-12-10 21:09 UTC, LostMojo commented
All fixed! Also moved the LO boxes out of the margins

![Screen Shot 2020-12-10 at 3.06.39 PM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/48cbfeb1-186f-4a65-98ad-089e246aa778)

2020-12-11 14:17 UTC, ajluk commented
@LostMojo I have noticed that the Travis builds failed due to changes added for Introduction page during regenerating recipes css files. If regenerate css files during resolving conflicts won't help there is a config variable I have created for Principles of Management (`$Config_hasGroupedIntroBody`), where was similar problem. You can try to use it in the accounting `_config.scss` file if the problem persists: 
![image](https://user-images.githubusercontent.com/55203598/101913681-963a5980-3bc3-11eb-93c6-daff1af3bc74.png). It has been added in the `_generator.scss` file as a hack solution to this condition when the template condition is not working properly.

2020-12-11 14:29 UTC, ajluk requested changes
Looks good! I have only left few comments with some suggestions and questions.

2020-12-11 14:29 UTC, ajluk commented on styles/books/accounting/book.scss
>      ChapterIntro: (
I would be more descriptive if you could change the name `ChapterIntro` to `ChapterIntroWithLO`.

2020-12-11 14:29 UTC, ajluk commented on books.txt
> +  "american-government-2e     american-government                9d8df601-4f12-4ac1-8224-b450bf739e5gif   col26739   easyvm5.cnx.org       mixins/"
@LostMojo I guess this uuid change for american government wasn't intentional. If yes it should be reverted.

2020-12-11 14:29 UTC, ajluk commented on yarn.lock
> +"@openstax/bakery-cli@^4.0.0":
@LostMojo I guess this change was intentional, but I'm asking just to be sure? :relaxed:

2020-12-11 15:09 UTC, LostMojo commented on yarn.lock
> +"@openstax/bakery-cli@^4.0.0":
It was not, thank you for catching these!

2020-12-11 22:08 UTC, LostMojo commented on styles/books/accounting/book.scss
>      ChapterIntro: (
It looks like changing it will break some of the ChapterIntro infrastructure that ChapterIntroWithLO is borrowing.

2020-12-14 12:54 UTC, ajluk commented on styles/books/accounting/book.scss
>      ChapterIntro: (
@LostMojo I guess the cause of this is that you need also add settings for the new shape in the `desing-setiings/cardboard/parts/_chapterintro-settings.scss` file like it was done for the ChapterIntro shape: 
![image](https://user-images.githubusercontent.com/55203598/102083483-ea3b7d00-3e13-11eb-9705-0a26fb03a488.png)

2020-12-14 16:18 UTC, LostMojo commented on styles/books/accounting/book.scss
>      ChapterIntro: (
Excellent! Thank you!!

2020-12-15 20:28 UTC, kswanson33 requested changes
The changes made regarding the outline itself look good! I left some comments about seemingly stray edits to other files.

2020-12-15 20:28 UTC, kswanson33 commented on yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Have a feeling that this file should not be deleted (but I don't actually know)

2020-12-15 20:28 UTC, kswanson33 commented on styles/books/accounting/book.scss
> +
Looks like there are two `Notes` sections now, with some overlap, likely from merging. Just make sure that all `includes` are present without repeats! :smile:

2020-12-15 22:26 UTC, LostMojo commented on recipes/output/business-ethics.css
> -
nope! reverting it

2020-12-15 22:26 UTC, LostMojo commented on styles/designs/cardboard/parts/_chapterintro-components.scss
> +        padding-right: .5rem,
ooo, yes!

2020-12-15 22:30 UTC, LostMojo commented on yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
This is one of the bois bein' reverted to it's past self

2020-12-16 19:13 UTC, LostMojo commented
Okay, this is going to be a whole lot nicer and have a much more sensible commit history if I start a new branch from the more recent zesty.zendaya so I'm moving the changes onto there (only on the files I want to change) and switching the pull request to that.

2020-12-17 08:36 UTC, closed without merging