style footnotes astronomy
openstax/cnx-recipes pull request #3189
Opened 2020-12-15 14:53 UTC by ajluk

Issue: #3027

2020-12-15 15:45 UTC, Stackblocks approved these changes

2020-12-15 20:48 UTC, kswanson33 requested changes

2020-12-15 20:48 UTC, kswanson33 commented on styles/books/astronomy/book.scss
> +@include use('Footnote', 'common:::FootnoteShape');
Looks like this is missing the include for `FootnoteCall`, but otherwise looks good! :)

2020-12-16 08:33 UTC, ajluk commented on styles/books/astronomy/book.scss
> +@include use('Footnote', 'common:::FootnoteShape');
Aww, I have missed it. Thank you!

2020-12-16 14:45 UTC, kswanson33 approved these changes

2020-12-17 15:05 UTC, merged