style accounting bands
openstax/cnx-recipes pull request #3195
Opened 2020-12-15 17:28 UTC by kswanson33

#3188

<img width="695" alt="image" src="https://user-images.githubusercontent.com/26280712/102249958-efaacd00-3ed0-11eb-8f9f-7ea8cc44b8a2.png">

2020-12-17 16:03 UTC, wilkus27 requested changes

2020-12-17 16:03 UTC, wilkus27 commented on styles/books/accounting/book.scss
> +  (pageName: eoc, firstSelector: '.os-eoc.os-section-summary-container', generalSelector: '.os-eoc'),
I think the first section in EOC is Key Terms. If I'm not wrong, selector is `glossary`.

2020-12-17 20:52 UTC, kswanson33 commented on styles/books/accounting/book.scss
> +  (pageName: eoc, firstSelector: '.os-eoc.os-section-summary-container', generalSelector: '.os-eoc'),
<img width="630" alt="image" src="https://user-images.githubusercontent.com/26280712/102540493-1b6ab600-407d-11eb-9824-3a0511b78b67.png">

You're right, the first EOC section is `.os-glossary-container`. For some reason I don't fully understand, it doesn't seem to matter what I put in `firstSelector` _or_ `generalSelector`; as long as the `pageName` is set to eoc, all of the eoc pages get the band (when building the pdf with prince). 

That being said, I'll make this change for now. I'd be interested in learning a bit more about this variable, and whether `firstSelector` and `generalSelector` are necessary for deployment?

2020-12-17 21:40 UTC, LostMojo reviewed
Looks pretty good-- but I'm curious why $bandColor is placed where it is

2020-12-17 21:40 UTC, LostMojo commented on styles/books/accounting/book.scss
> +$bandColor: #24739E;
Is there a reason the band color is here instead of in _colors.scss?

2020-12-17 21:53 UTC, kswanson33 commented on styles/books/accounting/book.scss
> +$bandColor: #24739E;
Good question! This is how it's done in all other books as well. From what I can tell, it has something to do with the framework design and compile order. I investigated, and found that when `$PagesWithBands` is non-empty, `$bandColor` must be defined in order for the imports from /designs and /design-settings to compile. I would imagine that there's probably a way to disentangle this, but it would require a more serious refactor.

2020-12-18 12:20 UTC, wilkus27 commented on styles/books/accounting/book.scss
> +  (pageName: eoc, firstSelector: '.os-eoc.os-section-summary-container', generalSelector: '.os-eoc'),
For `firstSelector` we apply additional property ` prince-page-group: start`. More details you can find in `bands.scss` file. Here is the path `styles > designs > common > pdf > bands.scss`. In this theme I think it doesn't matter. We don't apply specific settings for first pages of the group, but I think in one of the previous theme this property was necessery. Maybe in Carnival :thinking: I'm not sure. Here is also prince documentation about page groups: https://www.princexml.com/doc/11/advanced-paged/#page-groups.

2020-12-18 12:27 UTC, wilkus27 commented on styles/books/accounting/book.scss
> +$bandColor: #24739E;
@kswanson33 Yes, exactly, this is the reason. It requires too much work to refactor this, so we decided to hard code band color before imports.

2020-12-18 12:28 UTC, wilkus27 approved these changes

2020-12-21 18:00 UTC, LostMojo approved these changes

2020-12-21 18:02 UTC, merged