LO styling for accounting
openstax/cnx-recipes pull request #3222
Opened 2020-12-17 16:47 UTC by kswanson33

#2889

<img width="758" alt="image" src="https://user-images.githubusercontent.com/26280712/102517074-96bc6f80-405d-11eb-9052-c311c69a59a2.png">

2020-12-17 16:51 UTC, kswanson33 commented on recipes/books/accounting/_config.scss
> -(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO " counter(chapter) "." counter(section))
Question: I chose to change the recipe in order to remove the "LO" from the links. Is there a better way to do this?

2020-12-17 21:37 UTC, LostMojo approved these changes
Looks good! But you do seem to have added in some Astronomy changes along with the accounting?

2020-12-17 21:37 UTC, LostMojo commented on recipes/books/accounting/_config.scss
> -(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO " counter(chapter) "." counter(section))
Hm, I'm not aware of one-- but maybe one of the katalyst folks know?

2020-12-17 21:37 UTC, LostMojo commented on styles/books/astronomy/book.scss
> +    'H2Icon:::background': url(toDataUri("svg+xml", "designs/cardboard/resources/cardboard-summary2.svg")) no-repeat top left,
This PR is for Accounting LO-- did you mean to include Astronomy in it?

2020-12-17 21:37 UTC, LostMojo commented on styles/design-settings/cardboard/_colors.scss
> +    titleColorAstronomy: (_ref: "scheme:::P1"),
Same as before-- were these astronomy changes intended for this PR?

2020-12-17 22:11 UTC, kswanson33 commented on styles/design-settings/cardboard/_colors.scss
> +    titleColorAstronomy: (_ref: "scheme:::P1"),
Rebased!

2020-12-21 17:31 UTC, LostMojo approved these changes

2020-12-22 16:09 UTC, wilkus27 requested changes

2020-12-22 16:09 UTC, wilkus27 commented on recipes/books/accounting/_config.scss
> -(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO " counter(chapter) "." counter(section))
When we change something in the recipe it also has an impact on webview. So when we remove "LO" it will also disappear from here:

https://openstax.org/books/principles-financial-accounting/pages/1-multiple-choice
![image](https://user-images.githubusercontent.com/40228854/102907391-463a7d00-4476-11eb-9957-e467c5009ad7.png)

(when recipe changes be deploy to production). I don't know if we want to make such change there. Please contact with Larissa. 

If we don't want to change anything on webview we have to make bigger change in recipe.
We have to modify mixin related with target labels or create new one for custom labels to create something like that:

![image](https://user-images.githubusercontent.com/40228854/102908186-66b70700-4477-11eb-8066-552ff2c3aa31.png)

Then we can hide span with "LO" in styles adding `display:none` and instead of that add icon. It won't have an impact on webview.

I put LO and number in spans because I'm not sure if we can put divs inside the `<a>`.

2020-12-22 16:14 UTC, wilkus27 commented on recipes/books/accounting/_config.scss
> -(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO " counter(chapter) "." counter(section))
But probably spans will be better. We can also add some classes, like `os-text` and `os-number`.

2020-12-22 18:02 UTC, kswanson33 commented on recipes/books/accounting/_config.scss
> -(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO " counter(chapter) "." counter(section))
I like that idea. I'll split this into 2 issues, one for styles and one for the recipe update, so that the styles at least can be ready for merge before the break.

2021-01-04 14:30 UTC, wilkus27 approved these changes

2021-01-05 16:31 UTC, merged