Seperate label text from counter
openstax/cnx-recipes pull request #3317
Opened 2021-01-07 16:36 UTC by brittany-johnson

2021-01-07 16:41 UTC, brittany-johnson commented
@wilkus27 Hello! I requested your review specifically because I wanted to get your opinion. The change that I made in this PR affects all recipes. This is a large testing burden so I'm hesitant. If you have any suggestions, please let me know. 

If you agree w/ this change, the `config` files for each affected recipe will have to be updated with the `$labelCounter` property. @kswanson33 If we end up needing this I'll let you know so that you can finish up this issue. 

Thank you!

2021-01-11 14:21 UTC, wilkus27 requested changes
@brittany-johnson it looks good :relaxed: As I understand each label in each book will be changed to this format (separate label text and counter). I have concerns only about Polish books. I added comment about it :wink:

2021-01-11 15:21 UTC, kswanson33 approved these changes

2021-01-12 18:13 UTC, brittany-johnson commented on recipes/mixins/_link.scss
>          }
Yes I think that is a good idea to handle it in a separate PR, thanks!

2021-01-13 10:29 UTC, wilkus27 approved these changes

2021-01-13 16:43 UTC, merged