style sociology in the real world note
openstax/cnx-recipes pull request #3329
Opened 2021-01-11 17:44 UTC by kswanson33

#3197

![image](https://user-images.githubusercontent.com/26280712/104218299-8b652580-540a-11eb-9abb-e59bad6c5350.png)

2021-01-12 14:19 UTC, wilkus27 requested changes

2021-01-12 14:19 UTC, wilkus27 commented on styles/books/sociology/book.scss
> +        'Title:::padding-left': v-spacing(4) + 0.5,
For horizontal spacing we are using `h-spacing` function. If I remember correctly `h-spacing(1)=8px`. If we need custom value we just hard code it with comment why it's custom.

2021-01-12 14:19 UTC, wilkus27 commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +        padding-left: enum('ValueSet:::REQUIRED'),
Why this padding is set to REQUIRED and not hard coded? There will be other value for it in another notes? Just the question :wink:

2021-01-12 14:19 UTC, wilkus27 commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +        padding-right: v-spacing(1),
As I mentioned in my previous comment, for horizontal spaces we are using `h-spacing`.

2021-01-12 17:01 UTC, kswanson33 commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +        padding-left: enum('ValueSet:::REQUIRED'),
The padding is dependent on the icon size. Since position is absolute for the icon, I didn't see a good way to make the text line up next to the icon without doing it manually. So it wouldn't make sense to hard code the padding here without hard coding the icon size as well. Do you see a better way to do this - I admit I don't think it's a _great_ solution

2021-01-12 17:20 UTC, kswanson33 commented on styles/books/sociology/book.scss
> +        'Title:::padding-left': v-spacing(4) + 0.5,
So, the height and width of the title icon are set to v-spacing(4) since it needs to be square, and v-spacing(4) was used for a similar feature in carnival. The title text needs to be left-aligned next to the icon, with 0.5rem of additional spacing. So (with the current implementation) the same spacing should be used for all of them, whether it's v-spacing(4) or something else.

2021-01-13 11:46 UTC, wilkus27 commented on styles/books/sociology/book.scss
> +        'Title:::padding-left': v-spacing(4) + 0.5,
Hmm :thinking: For the icon I think it's ok to use v-spacing for width and heigh. It's something we used to do in previous themes. About icon and text, I got the same effect with such properties:

![image](https://user-images.githubusercontent.com/40228854/104446041-293b2a80-559a-11eb-982e-b91a5c27436b.png)

![image](https://user-images.githubusercontent.com/40228854/104446076-37894680-559a-11eb-97b4-21a463cfae1e.png)

I tried it just in the browser, so I'm not 100% sure if it works in PDF. But... I don't know if this solution is something we should go with. The goal is to achive some effect and it could be done in different ways :wink: My only concern was about the value of padding. We expect h-spacing and it's confusing in current form. I think it is ok to add just a comment that it's equal to width of icon plus h-spacing(1) (h-spacing(1)=8px=0.7rem=v-spacing(1)) and it will be ok. I'm curious what do you all think :slightly_smiling_face:

2021-01-13 11:55 UTC, wilkus27 commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +        padding-left: enum('ValueSet:::REQUIRED'),
I added comment above with proposition how we might do this without depending text on icon. But if you decide to stay with current solution I think it's ok to add just comment, that this value depends on icon and it's different in each note. :wink:

2021-01-13 16:04 UTC, ajluk commented on styles/books/sociology/book.scss
> +        'Title:::padding-left': v-spacing(4) + 0.5,
Yes, I think the same effect could be achieved different ways in styles. So both solutions are good here. The important thing as Natalia is writing above is to make comments where we are using some custom values etc.

2021-01-13 20:24 UTC, kswanson33 commented on styles/books/sociology/book.scss
> +        'Title:::padding-left': v-spacing(4) + 0.5,
Thanks @wilkus27 - this works, and I think it's a better solution!

2021-01-14 09:56 UTC, ajluk approved these changes

2021-01-14 13:39 UTC, wilkus27 approved these changes

2021-01-14 17:28 UTC, merged