style sociological research note
openstax/cnx-recipes pull request #3332
Opened 2021-01-11 21:55 UTC by kswanson33

#3200 

![image](https://user-images.githubusercontent.com/26280712/104242726-92515f80-542d-11eb-985e-310bdba9a879.png)

2021-01-12 14:38 UTC, wilkus27 requested changes

2021-01-12 14:38 UTC, wilkus27 commented on styles/output/sociology-pdf.css
> +
@kswanson33 I see that there is font-weight set to 500 for Archivo. Can you add this option to font import:

![image](https://user-images.githubusercontent.com/40228854/104328077-bf644780-54eb-11eb-9710-60dd58799fe5.png)

Previously I added only types which I have found in headers specs.

2021-01-12 17:38 UTC, kswanson33 commented on styles/output/sociology-pdf.css
> +
Thank you!

2021-01-13 09:14 UTC, wilkus27 approved these changes

2021-01-13 14:54 UTC, ajluk approved these changes

2021-01-14 19:31 UTC, merged