Issue 3186: Adding Sociology Tables
openstax/cnx-recipes pull request #3371
Opened 2021-01-14 16:51 UTC by LostMojo

#3186 using #3185 

<img width="736" alt="Screen Shot 2021-01-14 at 10 46 57 AM" src="https://user-images.githubusercontent.com/5740972/104621951-48978d80-5656-11eb-92e2-35983c5a8141.png">

2021-01-14 17:27 UTC, LostMojo commented
With current caption styling

![Screen Shot 2021-01-14 at 11.18.27 AM.png](https://images.zenhubusercontent.com/5fa9a1a8a99686b64c824016/11842aba-a76c-4dfc-9cd2-d009471c388f)

2021-01-18 11:37 UTC, ajluk requested changes
Everything looks good beside the doubled font needs to be removed in `typography.scss file`

2021-01-18 11:37 UTC, ajluk commented on styles/design-settings/cosmos/_typography.scss
>          titleOption2Font: ('IBM Plex Sans', sans-serif, StixGeneral),
@LostMojo The font you have added within this PR is already there under name `titleOption2Font`.

2021-01-19 15:40 UTC, Stackblocks approved these changes
Looks good once the doubled font is removed!

2021-01-19 22:54 UTC, LostMojo commented on styles/design-settings/cosmos/_typography.scss
>          titleOption2Font: ('IBM Plex Sans', sans-serif, StixGeneral),
Should we refactor the "titleOption1Font" font names into something more descriptive if they're going to be used for things besides titles?

2021-01-20 08:30 UTC, ajluk commented on styles/design-settings/cosmos/_typography.scss
>          titleOption2Font: ('IBM Plex Sans', sans-serif, StixGeneral),
Yes, it is a good idea! But if you will decide to do it, please remember to check where it has been used (could be many places now) and change it there too or I guess you can keep the old name (with a comment that this need to be cleaned) for now and  open up a clean up issue which we can take care of later? @Stackblocks what do you think?

2021-01-20 15:25 UTC, merged

2021-01-20 15:37 UTC, LostMojo commented on styles/design-settings/cosmos/_typography.scss
>          titleOption2Font: ('IBM Plex Sans', sans-serif, StixGeneral),
I went ahead and just changed the `sansFont` to `titleOption2Font` for easy refactoring later, and I think it would be best to just open up a new clean up issue, as it would affect more than just the tables.