style blockqote cosmos
openstax/cnx-recipes pull request #3406
Opened 2021-01-21 16:32 UTC by ajluk

Issues: #3277, #3404, #3405, #3276

2021-01-21 16:42 UTC, ajluk commented on styles/designs/cardboard/parts/_blockquotes-components.scss
> +        margin-right: 0.25in,
I have noticed there has been a typo made in the cardboard blockquote component margin property value unit as you can see above. I have regenerated and checked Business Ethics pdf file after I have fixed it and it hasn't changed the  styling, so I haven't created the separate issue for this fix, but let me know if you think It will be safer to do it: 
![image](https://user-images.githubusercontent.com/55203598/105381905-ce47aa00-5c0f-11eb-8f04-ad62f43a6f01.png)

2021-01-22 09:11 UTC, wilkus27 requested changes

2021-01-22 09:11 UTC, wilkus27 commented on styles/design-settings/cosmos/_design.scss
> +@import 'designs/cosmos/parts/learning-shapes';
I like this change :relaxed: It's more consistent now.

2021-01-22 09:11 UTC, wilkus27 commented on styles/designs/cardboard/parts/_blockquotes-components.scss
> +        margin-right: 0.25in,
Hmm interesting :thinking: I checked it in `-baked.scss` file and I noticed that there are such additional  default specs for blockquotes elements:

![image](https://user-images.githubusercontent.com/40228854/105470265-a43aca00-5c99-11eb-8984-5b0d59272218.png)

Maybe there are similar default specs added by Prince. That's why margin left and right don't work here (even they have proper values now). They might be overwritten by this default settings.

2021-01-22 15:40 UTC, kswanson33 approved these changes
Agree with the naming change request, but looks good otherwise!

2021-01-25 08:54 UTC, ajluk commented on styles/designs/cardboard/parts/_blockquotes-components.scss
> +        margin-right: 0.25in,
Yes, thank you Natalia! As we discussed I have checked that Prince also uses the default properties values predefined for html `blockquote` tag. I have reset the values to make Prince accept our own values (I asked Larissa if would like to do that to be sure that Prince uses values that give him).

2021-01-25 12:10 UTC, ajluk commented on styles/books/american-government/book.scss
> +@include use('Blockquote', "cosmos:::Blockquote");
Yes, good point! I have also changed the shape name in the previous theme for consistency.

2021-01-25 15:20 UTC, kswanson33 approved these changes

2021-01-26 13:43 UTC, wilkus27 approved these changes

2021-01-26 14:56 UTC, merged