Style connect the concepts note for psychology
openstax/cnx-recipes pull request #3411
Opened 2021-01-22 18:07 UTC by kswanson33

#3279 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/26280712/105528199-acebca00-5cb2-11eb-8d06-72b04d7f1489.png">

2021-01-25 08:37 UTC, ajluk requested changes
Everything looks good beside that the `box-decoration-break: slice` property is needed in this type of notes (with borders).

2021-01-25 08:37 UTC, ajluk commented on styles/books/psychology/book.scss
> +    // 'Container:::box-decoration-break': slice,
@kswanson33 The commented property from above is needed in this type of note to prevent adding bottom borders on every page when the note splits to the next pages.

2021-01-25 15:03 UTC, kswanson33 commented on styles/books/psychology/book.scss
> +    // 'Container:::box-decoration-break': slice,
Thank you! I've added it back in.

2021-01-25 16:18 UTC, ajluk approved these changes

2021-01-26 13:48 UTC, wilkus27 approved these changes

2021-01-26 16:24 UTC, merged