restyle introduction splash image
openstax/cnx-recipes pull request #3448
Opened 2021-01-29 18:07 UTC by ajluk

Issue:  #3312

2021-02-02 07:42 UTC, wilkus27 requested changes

2021-02-02 07:42 UTC, wilkus27 commented on styles/designs/cosmos/parts/_chapterintro-components.scss
>  $ChapterSplash__Media: empty_wrapper(SplashImgMedia, ' > span[data-type="media"]');
I think it should be removed (or renamed?). There is a component with the same name below.

2021-02-02 08:41 UTC, wilkus27 approved these changes

2021-02-03 22:43 UTC, LostMojo approved these changes

2021-02-05 09:08 UTC, merged