Remove margin in exercises paragraps cardboard
openstax/cnx-recipes pull request #3453
Opened 2021-02-02 11:35 UTC by ajluk

Issue:  #3330

2021-02-03 15:18 UTC, wilkus27 requested changes

2021-02-03 15:18 UTC, wilkus27 commented on styles/designs/cardboard/parts/_exercises-components.scss
> +
Can we use existing component? I think it makes the same change. It was added only to Answer Key shape. As I remember, I used `last-child` pseudo selector just in case that there is more then on paragraph in problem/solution.

2021-02-03 19:25 UTC, ajluk commented on styles/designs/cardboard/parts/_exercises-components.scss
> +
@wilkus27 as we discussed I have remove one of the paragraphs used in exercises/answerkey. I choosed the one with pseudo selector `:last-child` bacause after checking in the Answer Key in Business Ethics it appeared that there is only one para for each solution so nothing has changed.

2021-02-04 15:25 UTC, wilkus27 commented on styles/designs/cardboard/parts/_exercises-components.scss
> +
Yes, I think it's a good idea :slightly_smiling_face: :+1:

2021-02-05 15:47 UTC, kswanson33 approved these changes

2021-02-08 08:42 UTC, merged