style learning objectives principles economics
openstax/cnx-recipes pull request #3467
Opened 2021-02-04 15:12 UTC by ajluk

Issue: #3358

2021-02-04 15:52 UTC, ajluk commented on styles/design-settings/cosmos/parts/_learning-settings.scss
> +        ),
I have added Paragraph to this shape as well, because in Principles of Economics the markup is little different than it was for other books which have used this shape. Previously there was just a text node in the place of para. Let me know if I should rather create one shape for LO in modules instead and add different selectors to the books.scss files.

2021-02-05 10:00 UTC, wilkus27 requested changes

2021-02-05 10:00 UTC, wilkus27 commented on styles/design-settings/cosmos/parts/_learning-settings.scss
> +        ),
@ajluk I baked localy Economics to see this markup and I noticed that Learning Objectives is missing title. It should be added by this config: `$Config_abstractTitle: "Learning Objectives";` in `config.scss` file.

About markup, in carnival there was similar problem and there we decided to make changes in content, that is to wrap text into the paragraph in each book. BUT, it was necessary because paragraph had different style then list from below. Here we don't have such problem. I think it will be good to contant with Larissa and ask her if we want to have consistant markup. If not, I think your change is ok. I mean adding additional component to shape.

2021-02-05 11:26 UTC, ajluk commented on styles/design-settings/cosmos/parts/_learning-settings.scss
> +        ),
@wilkus27 Thank you! I don't know why I haven't noticed the missing title :sweat_smile:

2021-02-05 15:54 UTC, kswanson33 approved these changes

2021-02-05 21:04 UTC, LostMojo approved these changes

2021-02-08 08:49 UTC, wilkus27 approved these changes

2021-02-08 11:16 UTC, merged