style introduction page economics
openstax/cnx-recipes pull request #3491
Opened 2021-02-09 12:07 UTC by ajluk

Issues: #3360,  #3366, #3357, #3359, #3361, #3364

2021-02-12 14:16 UTC, ajluk commented on styles/designs/cosmos/parts/_titles-shapes.scss
> +));
I have created separate shape for titles in the Intro page, because in this book H3 headers arepresent there as well.

2021-02-17 16:05 UTC, wilkus27 requested changes

2021-02-17 16:05 UTC, wilkus27 commented on styles/designs/cosmos/parts/_learning-shapes.scss
> +    map-merge($LearningObjectives__Container, (
We have now to identical shapes:

![image](https://user-images.githubusercontent.com/40228854/108231212-d11bb900-7141-11eb-8a0b-bae2d3773d48.png)

I think we can remove one.

2021-02-18 09:53 UTC, wilkus27 approved these changes

2021-02-22 16:12 UTC, Stackblocks approved these changes

2021-02-23 10:27 UTC, merged