clean circled lists shapes corn
openstax/cnx-recipes pull request #3547
Opened 2021-02-23 13:29 UTC by ajluk

Issue: #2878

2021-02-23 13:35 UTC, ajluk commented on styles/designs/corn/parts/_lists-shapes.scss
> +
I have created two lists shapes used in exercises one for one column layout and second for 3 column layout. The  `ExercisesInOneColumnListsShape` covers also lists in Try It notes and Examples which contains exercises lists as well.
These shapes uses different settings for circled lists. To make this clear and usable I have also created separate circled lists components for both shapes.

2021-02-24 19:38 UTC, Stackblocks approved these changes

2021-02-24 19:38 UTC, Stackblocks commented on styles/design-settings/corn/parts/_lists-settings.scss
> +// Used for corcled lists in Try It Notes and Examples in all of the corn theme books, in Statistics books, where the exercises and solutions are in one column and in College Algebra Coreq for Coreq
"corcled" should be "circled"

2021-03-01 13:17 UTC, wilkus27 requested changes

2021-03-01 13:17 UTC, wilkus27 commented on styles/output/additive-manufacturing-pdf.css
> +  padding-right: 0.5rem; }
Is it intentional to add padding? The same change is in Statistics.

2021-03-01 13:17 UTC, wilkus27 commented on styles/design-settings/corn/parts/_lists-settings.scss
>          _selectors: ('[data-type="problem"]'),
Previously it was added only in Statistics and in College Algebra Coreq to one section, which was specified in book.scss file: 

![image](https://user-images.githubusercontent.com/40228854/109501367-c6ddb100-7a97-11eb-8060-a0e19d63b63f.png)

So it was ok to use only `[data-type="problem"]` selector here. Now, when we apply these settings to books which contain multicolumn sections this selector is too general. Some of the properties might be overwritten.

2021-03-01 13:47 UTC, ajluk commented on styles/design-settings/corn/parts/_lists-settings.scss
>          _selectors: ('[data-type="problem"]'),
@wilkus27 I have checked and it appears that is not overwriting the different styles for the lists applied to sections with 3 column layout. I think that is because their selectors are more specific/strong, but thank you for pointing this out. I had it in my mind as well.

2021-03-03 08:47 UTC, ajluk commented on styles/output/additive-manufacturing-pdf.css
> +  padding-right: 0.5rem; }
@wilkus27 As we discussed the padding doesn't do any harm if the list in one column exercises, I'm not sure what was the the intention of adding it (probably there was a sibling to this list positioned next to it somewhere), but it was there before my changes from this PR, just not in the output pdf-css files for some reason. But thank you for pointing this out!

2021-03-03 19:30 UTC, wilkus27 commented on styles/design-settings/corn/parts/_lists-settings.scss
>          _selectors: ('[data-type="problem"]'),
Hmm @ajluk I think it's still too general :crying_cat_face: Some books contain section exercises, which use multicolumn shape. They are children of `[data-type="page"]`.

![image](https://user-images.githubusercontent.com/40228854/109860538-94ca7b80-7c5e-11eb-9948-306d48b69230.png)

If I'm not wrong it's `[data-type="page"] > section.os-eos [data-type="problem"]`. So for books with section exercises we should probably use `[data-type="page"] > section:not(.os-eos) [data-type="problem"]` for `ExercisesProblemLists` .

2021-03-08 10:30 UTC, ajluk commented on styles/design-settings/corn/parts/_lists-settings.scss
>          _selectors: ('[data-type="problem"]'),
@wilkus27 Oh, yes that's a very good point! Thank you! I've got this in the back of my head and in the end I have forgot about those section guys :sweat:

2021-03-11 11:56 UTC, wilkus27 approved these changes

2021-03-15 14:13 UTC, merged