clean chapter intro shapes
openstax/cnx-recipes pull request #3557
Opened 2021-02-24 18:09 UTC by ajluk

Issue:  #2180

2021-03-01 13:53 UTC, wilkus27 requested changes
I'm leaving some suggestions for captions. Let me know what do you think :wink: There is a lots of changes here, so I don't finish my review yet. I'll come back to it tomorrow with fresh head :smile:

2021-03-01 13:53 UTC, wilkus27 commented on styles/designs/carnival/parts/_caption-components.scss
> +        padding-bottom: enum('ValueSet:::OPTIONAL'),// Used in Chapter Intro
In next themes we decided that we use OPTIONAL/REQUIRED only to a few properties in a component. If there is a lots of them, then it's better to create a few different components which can contain hard coded properties. So maybe we can create here `$Caption__Container--Figures`, `$Caption__Container--Tables`, `$Caption__Container--ChapterIntro`. What do you think? In my opinion it will be more clear and readable.

2021-03-01 13:53 UTC, wilkus27 commented on styles/designs/carnival/parts/_caption-components.scss
>  $Caption__Title--Label: (
I think it should changed to `$Caption__Title__Label`.

2021-03-01 13:53 UTC, wilkus27 commented on styles/designs/carnival/parts/_caption-components.scss
> +        margin-right: enum('ValueSet:::OPTIONAL'), // Used in Figures, Chapter Intro not in Tables
I would split this also to a few components. There is too many optionals here.

2021-03-05 09:26 UTC, wilkus27 requested changes
Here are bunch of new comments :D Most of them are propositions. Let me know what do you think about it :wink: Still I have a few files to review from this PR, so I don't remove my assignment.

2021-03-05 09:26 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +    _name: "ChapterOutlineObjectiveText",
Or `$ChapterOutline--Margin__Objective__Text`. I don't know what would be better :thinking:

2021-03-05 09:26 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterOutline__Objective--Learning: empty_wrapper(OutlineObjectiveLearning, ' > .learning-objective');
As I see it's only in Full Width Chapter Outline. Maybe it could be `$ChapterOutline--FullWidth__ObjectiveLearning` or `$ChapterOutline--FullWidth__Objective__Learning` . Part `Objective--Learning` isn't proper, since Learning is not type of Objective, but its child. If I understand correctly from the shape: 

![image](https://user-images.githubusercontent.com/40228854/110093074-9ac57700-7d9a-11eb-9384-0ff9f136ce29.png)

2021-03-05 09:26 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +        _name: "SplashCaptionBg",
Can we keep the naming convention for Splash Image components? It could be `$ChapterSplash__FigureBg` and `$ChapterSplash__CaptionBg`.

![image](https://user-images.githubusercontent.com/40228854/110094685-5fc44300-7d9c-11eb-9bb9-d0efbfd8defe.png)

2021-03-05 09:26 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +        _name: "SplashCaptionBg",
Hmm... there is component `$ChapterSplash__Figure` so maybe it should be `$ChapterSplash__Figure__Bg` or `$ChapterSplash__FigureBg` :thinking: I'm not sure which convention is better.

2021-03-07 10:26 UTC, wilkus27 requested changes

2021-03-07 10:26 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
>      _subselector: ' > .os-chapter-outline',
As we discussed with @ajluk , since this PR is so huge already, we want to fix only problems like nested components, unnecessary functions and to split components containing too many OPTIONALs. There will be created separate issue for changing naming convention if we decide that we want to change something :wink: 

Please, leave your thoughts about it :slightly_smiling_face:

2021-03-07 10:26 UTC, wilkus27 commented on styles/output/ap-biology-pdf.css
> +  font-family: IBM Plex Serif, serif;
This is a new property here. Is it intentional?

2021-03-07 10:26 UTC, wilkus27 commented on styles/output/biology-pdf.css
> +  font-size: 1.2rem;
Here is the new property for this element. Is it intentional? If so, shouldn't be added also for `.os-title-label` and `.os-title`? Maybe we should also define line height?

2021-03-08 08:22 UTC, ajluk commented on styles/output/ap-biology-pdf.css
> +  font-family: IBM Plex Serif, serif;
@wilkus27 previously there was 12px, but here I have just used function we dedicated to this: font-size: font-scale(0) so the value is 1 rem (in this case 12px as well): 
![image](https://user-images.githubusercontent.com/55203598/110294148-c2614d00-7fef-11eb-8443-078e0e48969c.png)

2021-03-08 08:25 UTC, wilkus27 commented on styles/output/ap-biology-pdf.css
> +  font-family: IBM Plex Serif, serif;
I mean font family :smile: It wasn't defined before.

2021-03-08 08:28 UTC, ajluk commented on styles/output/ap-biology-pdf.css
> +  font-family: IBM Plex Serif, serif;
@wilkus27 It was there previously in the title settings file, but for some reason wasn't in the output. It doesn't change anything actually, because the font is the base font family.

2021-03-08 08:32 UTC, ajluk commented on styles/output/biology-pdf.css
> +  font-size: 1.2rem;
@wilkus27 Thank you! It is a typo.

2021-03-08 10:25 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
>      _subselector: ' > .os-chapter-outline',
Yes, that's a good idea, especially since this PR is also needed as a base PR for https://github.com/openstax/cnx-recipes/pull/3658. Thank you! I will open a separate PR with a description and links to you comments about changing naming convention after this one will be approved.

2021-03-11 12:00 UTC, wilkus27 approved these changes

2021-03-11 16:26 UTC, Stackblocks approved these changes

2021-03-15 11:58 UTC, merged