[WIP] recipe and styles eng comp
openstax/cnx-recipes pull request #3617
Opened 2021-03-02 21:49 UTC by brittany-johnson

https://github.com/openstax/cnx-recipes/issues/3483

2021-03-08 19:08 UTC, brittany-johnson commented on recipes/mixins/_modify.scss
> +    class: attr(class) " chapter-content-module"
usually, there are no classes present on `data-type=page` so it was not an issue previously that this line was deleting any present classes before injecting `chapter-content-module` but in eng-comp there is a class that needs to persist

2021-03-10 21:35 UTC, kswanson33 approved these changes

2021-03-11 12:12 UTC, ajluk commented on books.txt
> +  "english-composition      english-composition                  90b8e437-4f53-4d85-9558-2e870009f441   col10001   content06.cnx.org    mixins/                   cosmos"
@brittany-johnson I'm not sure if it is needed at this point, but I noticed that the first column in `book.txt` file hasn't been updated by you:
![Uploading image.png…]()

2021-03-11 12:27 UTC, ajluk approved these changes
@brittany-johnson Everything looks good! A lot of work was done here! :open_mouth: : I just left few comments, but they are not pointing any breaking changes.

2021-03-11 12:27 UTC, ajluk commented on styles/designs/cosmos/parts/_chapterintro-components.scss
> +        margin-left: 2rem,
@brittany-johnson Could I ask you out of curiosity what was the reason for adding these properties? I tried to compare psychology pdf file with english composition pdf generated on this branch and couldn't spot the difference :smile:

2021-03-11 12:27 UTC, ajluk commented on recipes/books/_release.scss
@brittany-johnson I guess the `move-footnotes` and `modify-column-container` can be also safely enabled for this book.

2021-03-11 13:32 UTC, wilkus27 requested changes
@brittany-johnson Most of the things looks good :relaxed: I just left a few comments and questions.

2021-03-11 13:32 UTC, wilkus27 commented on recipes/books/english-composition/_config.scss
> +);
I have a question about exercises:

![image](https://user-images.githubusercontent.com/40228854/110788933-918f4b00-826f-11eb-8eaa-fd080561429a.png)

They are now at the end of the modules. Should they be EOS or EOC exercises? If EOS we have a special config for end of section exercises.

2021-03-11 13:32 UTC, wilkus27 commented on recipes/books/english-composition/_config.scss
> +$Config_abstractTitle: "Learning Objectives";
I think we can remove it. There is no abstract in this book. It contains Learning Objectives created in the content (not in the metadata) and it has already title "Learning Outcomes".

2021-03-11 13:32 UTC, wilkus27 commented on recipes/books/english-composition/_config.scss
> +$Config_ContentExercise_TitleContent : (os-divider: ".", os-number : counter(exerciseMaybeInContent));
This one is related with my previous comment about Discussion Questions. If these exercises should be moved to EOS or EOC, I think we can remove this config.

2021-03-11 13:32 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +@include use('ChapterIntroWithLO', 'cosmos:::ChapterIntroWithLOShape');
Is it intentional? We are using one shape for Chapter Intro per book.

2021-03-11 13:32 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +@include use('TocUnit', 'cosmos:::TocUnitShape');
For books with units we added also this include:
```
@include use('UnitTitle', 'common:::Hidden');
```
to hide unit title from inside of the book.

2021-03-11 13:32 UTC, wilkus27 commented on styles/designs/cosmos/parts/_chapterintro-components.scss
> +        margin-left: 2rem,
It will have an impact on all books from Cosmos theme. Is it intentional?

2021-03-11 13:32 UTC, wilkus27 commented on styles/designs/cosmos/parts/_titles-components.scss
> +    _subselector: ' > h3:not(.os-title)',
Hmm :thinking: For some reason after this change styles for Learning Outcomes title are overwritten :eyes: 

![image](https://user-images.githubusercontent.com/40228854/110793529-02853180-8275-11eb-9249-90ae2776e169.png)

2021-03-11 13:32 UTC, wilkus27 commented on RELEASE_FLAGS.md
> +| english-composition | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_
Since this book contains footnotes, I think it will be good to enable also `move-footnotes` flag :thinking:

2021-03-11 13:49 UTC, wilkus27 commented on recipes/books/english-composition/_config.scss
> +  (className: "further-reading", clusterBy: $CLUSTER_NONE, name: "Further Reading"),
I just noticed in documentation that there are links to sections. I'm not sure if Larissa want them or not. Maybe we should change `$CLUSTER_NONE` to `$CLUSTER_SECTION`? I don't know :thinking: 

![image](https://user-images.githubusercontent.com/40228854/110797024-eedbca00-8278-11eb-940e-9c74cb24afb2.png)

https://github.com/openstax/cnx-recipes/issues/3214

2021-03-11 13:53 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +//EoB
I don't see styles for EOC modules. Probably they should use this shape:

![image](https://user-images.githubusercontent.com/40228854/110797490-6ad61200-8279-11eb-856b-3bc7e6127146.png)

2021-03-11 14:52 UTC, brittany-johnson commented on books.txt
> +  "english-composition      english-composition                  90b8e437-4f53-4d85-9558-2e870009f441   col10001   content06.cnx.org    mixins/                   cosmos"
Oh I didn't notice that, thank you!

2021-03-11 21:22 UTC, brittany-johnson commented on styles/designs/cosmos/parts/_chapterintro-components.scss
> +        margin-left: 2rem,
Good question, I had to look back to remember why I put that there LOL! 
This is for when an outline objective is long and is more than one line. Larissa requested that the second line is indented to be inline with the text.
The pictures below are with and without: 
<img width="783" alt="Screen Shot 2021-03-11 at 3 19 08 PM" src="https://user-images.githubusercontent.com/24909007/110856621-7deae100-827d-11eb-80b3-269f39ca6a97.png">
<img width="789" alt="Screen Shot 2021-03-11 at 2 51 43 PM" src="https://user-images.githubusercontent.com/24909007/110856624-7e837780-827d-11eb-87a6-94141f45ebe4.png">

2021-03-11 21:24 UTC, brittany-johnson commented on recipes/books/english-composition/_config.scss
> +);
Ah! There are EOS - I'll switch the config. Thanks!

2021-03-11 21:33 UTC, brittany-johnson commented on recipes/books/english-composition/_config.scss
> +$Config_ContentExercise_TitleContent : (os-divider: ".", os-number : counter(exerciseMaybeInContent));
I think the exercises are in the correct place now - at least that was the feedback I got when I sent the PDF for review.
Without this config option, the number label is not correct - it says `Exercise 1` instead of `1.`

2021-03-11 21:33 UTC, brittany-johnson commented on styles/books/english-composition/book.scss
> +@include use('ChapterIntroWithLO', 'cosmos:::ChapterIntroWithLOShape');
Oops! No this was a mistake, thank you!

2021-03-11 21:41 UTC, brittany-johnson commented on styles/designs/cosmos/parts/_chapterintro-components.scss
> +        margin-left: 2rem,
Yes, this is for when the objective is longer than 1 line. I left some screenshots responding to a comment above

2021-03-11 21:43 UTC, brittany-johnson commented on styles/designs/cosmos/parts/_titles-components.scss
> +    _subselector: ' > h3:not(.os-title)',
Oh no 😭

2021-03-11 21:45 UTC, brittany-johnson commented on recipes/books/english-composition/_config.scss
> +  (className: "further-reading", clusterBy: $CLUSTER_NONE, name: "Further Reading"),
Not for english comp[ according to this card ](https://github.com/openstax/cnx-recipes/issues/3541)

2021-03-11 21:51 UTC, brittany-johnson commented on styles/designs/cosmos/parts/_titles-components.scss
> +    _subselector: ' > h3:not(.os-title)',
I added this because it was affecting another h3. I'll just remove it for now and it can be fixed in another PR later.

2021-03-11 22:42 UTC, brittany-johnson commented
Thanks again for reviewing! I've addressed most comments but there are 1-2 things I'll do in another PR so I can unblock Kendra

2021-03-11 23:18 UTC, merged