Style notes for world history
openstax/cnx-recipes pull request #3675
Opened 2021-03-10 22:14 UTC by kswanson33

2021-03-15 17:05 UTC, ajluk requested changes
Everything looks good, but the conflicts havn't been entirely resolved in the output pdf files, so the styles should be regenerated.

2021-03-15 17:05 UTC, ajluk commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +
@kswanson33 I was wandering if this list should be moved to `list-components` file? We usually move components like lists, table components, captions to its own components files. But this one is very specific. What do you think?

2021-03-15 17:05 UTC, ajluk commented on styles/output/world-history-pdf.css
> +<<<<<<< HEAD
I guess the styles should be regenerated, because the conflicts hasn't been entirely resolved in this file.

2021-03-15 18:25 UTC, kswanson33 commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +
The reason why I haven't put it in `list-components` is that the color of the top border depends on the parent note's title color, as in this example:

![image](https://user-images.githubusercontent.com/26280712/111201885-3c19ad80-8591-11eb-9f63-572212148ada.png)

I don't think there's a way for this component to exist outside of the note shape and still based the border color on the parent note color.

2021-03-15 18:25 UTC, kswanson33 commented on styles/output/world-history-pdf.css
> +<<<<<<< HEAD
Thanks! I'll fix it when I do the final conflict resolution.

2021-03-16 12:48 UTC, ajluk commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +
I'm not sure if I understand correctly your question, but we can put such component to `lists-components`  and then import `list-components` in `note-shapes` (boxed notes shapes), then set the color in the `settings` or in this case in the `book.scss` file. But if you think it is better to keep this in the `notes-components` I guess it also acceptable, because of the specificity :slightly_smiling_face:

2021-03-16 12:50 UTC, ajluk approved these changes

2021-03-16 13:41 UTC, wilkus27 approved these changes

2021-03-16 14:12 UTC, kswanson33 commented on styles/designs/cosmos/parts/notes/_notes-components.scss
> +
OH you are very smart. Thanks 😄

2021-03-16 14:47 UTC, merged