refactor titles shapes and components in carnival
openstax/cnx-recipes pull request #3693
Opened 2021-03-15 10:37 UTC by wilkus27

Issue: https://github.com/openstax/cnx-recipes/issues/2169

2021-03-15 11:34 UTC, wilkus27 commented on styles/books/pl-u-physics/book.scss
> -
I fixed also spacing in this file. Code wasn't aligned to the left. That's why it shows that everything here is changed.

2021-03-15 11:57 UTC, wilkus27 commented on styles/designs/carnival/parts/_appendix-components.scss
> +
Please, let me know what is your opinion. Appendix Glossary is module that appears just in one book (Microbiology):

![image](https://user-images.githubusercontent.com/40228854/111148523-04f4cd80-858c-11eb-8d0d-6135f61243b3.png)

Now Appendix shape contains titles components (which I'm removing within this PR), lists components (which will be moved to lists shapes in another PR) and appendix glossary components. When all clean up things will be done we can do two things:
1. keep `AppendixShape` just with appendix glossary components, maybe rename it to AppendixGlossaryShape and inlude it only for Microbiology (old one should be removed from other book.scss files) 

or

2. remove all appendix files and add appendix glossary list component to `PagesListsShape` and title component to `PagesTitlesShape`.

Let know which solution is better. When we have a decision, I will create clean up issue for that.

2021-03-17 09:58 UTC, ajluk requested changes
@wilkus27 Everything looks good beside the doubled `preface` class which I'm not sure where it came from. A huge work has been done here! :slightly_smiling_face:

2021-03-17 09:58 UTC, ajluk commented on styles/output/anatomy-pdf.css
> +.preface.preface {
@wilkus27 There is a second preface class added, I guess it is by accident.

2021-03-17 09:58 UTC, ajluk commented on styles/designs/carnival/parts/_answerkey-shapes.scss
> -        $H1,                                                           //ToDo: create separate shape for EOB titles, like in other themes
@wilkus27 I guess this comment on the right could be removed, because I have seen that you already created the title shape for EoB part.

2021-03-17 09:58 UTC, ajluk commented on styles/output/anatomy-pdf.css
> +.preface.preface {
I have checked out locally to your branch and this bug is really odd, because in the settings file only one selector is adder and the second one only appears in the output files (for all of the books), maybe regenerating output files could help with that :thinking:

2021-03-17 09:58 UTC, ajluk commented on styles/designs/carnival/parts/_appendix-components.scss
> +
I guess if the shape is needed only in one book, we can keep it, if we will remove it, we need to set the glossary title color to `OPTIONAL` or `REQUIRED` and then set it for every book even it's not needed there. But that is just a thought how to keep it simple and the second preposition is also ok, because it is consistent to what we do in the other themes and you can add just a comment that the title is used only in Microbiology.

2021-03-17 11:32 UTC, wilkus27 commented on styles/design-settings/carnival/parts/_preface-settings.scss
>  ));
Selector is defined in `Preface__Container` component which I moved to `titles-components`. We are using it in `PageTitlesShape`. It's not a perfect solution. Selector should be defined in settings. But because we are going to remove this entire file (when clean up for lists be done) I decided to remove selector from here, rather then create `preface-components` file with different empty `Preface__Container` component.

2021-03-17 11:36 UTC, wilkus27 commented on styles/output/anatomy-pdf.css
> +.preface.preface {
Thank you @ajluk for noticing that. I made a fix and add some comment.
Generally this problem appeared because selector was defined in Preface settings (which are going to be removed) and in `Preface__Container`. We need class in this component, because we are using it in `PageTitlesShape`.

2021-03-17 11:39 UTC, wilkus27 commented on styles/designs/carnival/parts/_answerkey-shapes.scss
> -        $H1,                                                           //ToDo: create separate shape for EOB titles, like in other themes
Yes, entire line is already removed.

2021-03-17 11:47 UTC, wilkus27 commented on styles/designs/carnival/parts/_appendix-components.scss
> +
Thank you @ajluk! Yeah, you are right, first solution seems to be more simple and clear. @kswanson33 I saw you have done something similar for World History from Cosmos. It looks very good. I can create a card to apply your solution to Carnival theme.

2021-03-18 08:04 UTC, ajluk approved these changes

2021-03-24 09:33 UTC, merged