fix chapter intro components names
openstax/cnx-recipes pull request #3763
Opened 2021-03-25 16:26 UTC by ajluk

Issue: #3740

2021-03-25 22:00 UTC, Stackblocks approved these changes

2021-03-26 09:44 UTC, wilkus27 requested changes
@ajluk I left a few comments. I'm not sure about some components if they are types of other components or if they are separate elements. So I'm not sure about using `--` vs `__` in their names. Let me know your thoughts :relaxed:

2021-03-26 09:44 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +);
I'm not sure about these components. Link and Text are types of Objective or they are elements? If they are elements I think it should be `$ChapterOutline--Margin__Objective__Link` or `$ChapterOutline--Margin__ObjectiveLink`.

2021-03-26 09:44 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +    _name: "OutlineFullWidthObjectiveLink",
Same question for this component.

2021-03-26 09:44 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterOutline--FullWidth__Objective--Learning: empty_wrapper(OutlineFullWidthObjectiveLearning, ' > .learning-objective');
This one is the most confusing :grin: Is Learning a type of Objective? I know there could be Chapter Objective or Learning Objective. Is this that case? Or `.learning-objective` is one of a child of Chapter Objectives element?

2021-03-26 09:44 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterSplash__Figure--Bg: (
Does Bg describe type of figure (it could be with or without background) or background of figure, so one of the element of the figure?

2021-03-26 09:44 UTC, wilkus27 commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterSplash__Caption--Bg: (
Same question here.

2021-04-09 07:39 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +);
@wilkus27 The link is a child of `div.os-chapter-objective`, but has the same class :woozy_face: : 
![image](https://user-images.githubusercontent.com/55203598/114145816-217bef80-9917-11eb-8b2c-bb680c10a201.png)
The `$ChapterOutline--Margin__Objective--Text` on the other hand is a child of the link itself.

2021-04-09 07:47 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +    _name: "OutlineFullWidthObjectiveLink",
Here also I changed the name to `$ChapterOutline--FullWidth__Objective__Link`

2021-04-09 08:05 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterOutline--FullWidth__Objective--Learning: empty_wrapper(OutlineFullWidthObjectiveLearning, ' > .learning-objective');
@wilkus27 This is just a wrapper div with class `.learning-objective` which is a child of `div.chapter-objective`:
![image](https://user-images.githubusercontent.com/55203598/114149115-d532ae80-991a-11eb-98d2-e62f1b86b4b4.png)

2021-04-09 09:22 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterSplash__Figure--Bg: (
It is the `::before` pseudo element, a first child of figure, so in this case I changed the name to `ChapterSplash__Figure__Bg`. Thanks!

2021-04-09 09:54 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +$ChapterSplash__Caption--Bg: (
See above, also left the name as it was, because of the same reason.

2021-04-12 11:47 UTC, wilkus27 approved these changes
Everything looks good :relaxed: A lot of work is done here :muscle:

2021-04-14 12:03 UTC, merged