create recipe snippet files and add  basic styles from business ethic…
openstax/cnx-recipes pull request #3810
Opened 2021-04-08 09:42 UTC by ajluk

for #3772

2021-04-14 16:10 UTC, ajluk commented on styles/design-settings/cardboard/parts/_table-settings.scss
> +        ),
The middle header row tds shoud have the same specs as second header rows #2741

2021-04-14 16:17 UTC, ajluk commented on styles/design-settings/cardboard/parts/_table-settings.scss
> +        ),
The middle header row tds should have the same specs as second header rows #2741 for default/top tiled tables.

2021-04-14 16:18 UTC, ajluk commented on styles/design-settings/cardboard/parts/_table-settings.scss
> +        ),
See the comment from above.

2021-04-14 16:18 UTC, ajluk commented on styles/design-settings/cardboard/parts/_table-settings.scss
> +        ),
Similarly the middle header rows tds in text-heavy tables should also have the same specs as second header rows specified in #2741.

2021-04-20 15:29 UTC, wilkus27 requested changes

2021-04-20 15:29 UTC, wilkus27 commented on recipes/books/bca/_config.scss
> +$Config_hasCompositeAppendixes: true;
This is old config variable that is not used anymore. It can be removed.

2021-04-20 16:07 UTC, wilkus27 approved these changes

2021-04-27 15:14 UTC, brittany-johnson approved these changes

2021-04-28 13:53 UTC, merged