Add Finance Styling
openstax/cnx-recipes pull request #3814
Opened 2021-04-09 21:14 UTC by LostMojo

Documentation: #3662

2021-04-09 21:41 UTC, LostMojo commented
Yes, this is the whole finance book. Sorry about that

2021-04-13 15:16 UTC, ajluk commented on recipes/books/finance/_config.scss
> +(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO ", labelCounter: counter(chapter) "." counter(section))
@LostMojo If this config is needed in finance recipe not just copy/pasta form other book recipe, the flag `seperate-label-text` should be also enabled for finance.

2021-04-13 15:21 UTC, ajluk commented on styles/designs/cardboard/parts/_hljs-components.scss
> +$Code__Container: empty_wrapper(CodeContainer, '');
@LostMojo I can't see if the components is used anywhere, maybe the one below it was your first thought.

2021-04-13 16:15 UTC, LostMojo commented on styles/designs/cardboard/parts/_hljs-components.scss
> +$Code__Container: empty_wrapper(CodeContainer, '');
Thanks for catching that!

2021-04-13 16:24 UTC, ajluk requested changes
A lot of work has been done here! I left some comments here and there.

2021-04-13 16:24 UTC, ajluk commented on styles/designs/cardboard/parts/_lists-components.scss
> +        content: '"Step " counter(list-item) ". "',
@LostMojo Instead adding counter via the styles you could use ```$Config_CustomList: (
  (selector: '.stepwise', name: "stepwise", beforeLabel: "Step ", afterLabel: ". "),
);``` in the config.scss file and enabled related flag `custom-lists` for finance.

2021-04-13 16:24 UTC, ajluk commented on styles/designs/cardboard/parts/_table-shapes.scss
> +@include create_shape('cardboard:::ColoredBgTableRowShape', (
That's an interesting solution! But what concerns me that it can be overwritten by other styles if this component isn't included in the table shapes. I think for safety reasons it should be rather included in the table shapes that could have such functionality. What do you think?

2021-04-13 16:24 UTC, ajluk commented on styles/designs/cardboard/parts/_calculator-components.scss
> +        // display: block,
I guess this comment could be removed.

2021-04-15 14:03 UTC, LostMojo commented on styles/designs/cardboard/parts/_table-shapes.scss
> +@include create_shape('cardboard:::ColoredBgTableRowShape', (
I'll go ahead and incorperate it into the larger table shape 😅

2021-04-15 15:32 UTC, LostMojo commented on styles/designs/cardboard/parts/_table-shapes.scss
> +@include create_shape('cardboard:::ColoredBgTableRowShape', (
I originally put it separately so that other colors could be included with different shapes, but I don't see us using more than one color at the moment. Incorporating it into an existing shape will probably mean that the color will have to be an optional variable, so it won't break any past books, though.

2021-04-15 20:13 UTC, LostMojo commented
Fixes incorporated!

2021-04-20 11:45 UTC, wilkus27 requested changes
@LostMojo I added some comments. Some small fixes are needed, but in general it looks good. A lot of work is done here :slightly_smiling_face: 

Beside problems from comments I noticed that output files for other books are not generated. Can you use `./script/run ./script/build-styles` command for this? 

Also when we change something in release flags we should generate `RELEASE_FLAGS.md` file. To do that run `./script/run ./script/release-flag-chart`.

2021-04-20 11:45 UTC, wilkus27 commented on styles/designs/cardboard/parts/_lists-components.scss
> +        // display: inline-block,
I think it can be removed.

2021-04-20 11:45 UTC, wilkus27 commented on styles/designs/cardboard/parts/_lists-components.scss
> +);
Can we remove commented line? If so, then this component will have no properties. In such cases we are using `empty_wrapper`:

`$StepwiseList--Content: empty_wrapper(StepwiseListContent, ' > .os-stepwise-content');`

2021-04-20 11:45 UTC, wilkus27 commented on styles/designs/cardboard/parts/_lists-shapes.scss
> +));
In general, we are using `--` in names to describe variations of some components. E.g tag `td` in tables :

```
$Table__Data--TopAligned,
$Table__Data--LeftAligned,
$Table__Data--RightAligned,
$Table__Data--Centered
```
When we want to describe different elements we should use `__`. Using example from tables:

```
$Table__Container
$Table__Head
$Table__Data
```

Sometimes it is hard to say if component is a variation or separate element :smile: Can you check names of all of your newly created components whether they are going with this convention? I think components from this file and `hljs_components` might need some fixes.

2021-04-20 11:45 UTC, wilkus27 commented on styles/designs/cardboard/parts/_table-components.scss
> +    _subselector: " > table.timeline-table",
Here is a good example with proper use of `--` in name. :slightly_smiling_face: :+1: We have regular `Table` and its variation `Table--Timeline`.

2021-04-20 11:45 UTC, wilkus27 commented on styles/designs/cardboard/parts/notes/_notes-iconCondensed-shapes.scss
> +@import '../lists-components';
Do we need this import? Shape contains only notes components.

2021-04-20 14:09 UTC, LostMojo commented on recipes/books/finance/_config.scss
> +(selector: 'div[data-type="chapter"] > div[data-type="page"]:not(.introduction)', labelText: "LO ", labelCounter: counter(chapter) "." counter(section))
(added to seperate-label-text)

2021-04-20 15:28 UTC, LostMojo commented on styles/designs/cardboard/parts/notes/_notes-iconCondensed-shapes.scss
> +@import '../lists-components';
We do not! good catch

2021-04-21 07:56 UTC, wilkus27 approved these changes

2021-04-21 23:30 UTC, merged