rm soc answer key section if not present
openstax/cnx-recipes pull request #3829
Opened 2021-04-19 19:42 UTC by brittany-johnson

related issue https://github.com/openstax/cnx-recipes/issues/3822

2021-04-22 08:12 UTC, wilkus27 requested changes
I left two questions :slightly_smiling_face:

2021-04-22 08:12 UTC, wilkus27 commented on recipes/books/_generator.scss
> +  @include utils_clearTrash();
I'm not sure about this include. This change appears in all books. I'm wondering if clearing trash in earlier pass might have some unpredictable results :thinking: Maybe we can put it under `if` statement from `732` line? What do you think? Than it will have impact only on sociology which is going to be tested carefully in the near future. Let me know your thoughts :wink:

2021-04-22 08:12 UTC, wilkus27 commented on recipes/books/american-government/_config.scss
> +$Config_hasGroupedIntroBody: true;
Is it intentional? If so, I checked output file for American Government and it doesn't change anything there :thinking:

2021-04-23 21:55 UTC, philschatz approved these changes

2021-04-24 00:13 UTC, merged