Add contemporary-math to the corn theme
openstax/cnx-recipes pull request #3836
Opened 2021-04-26 16:57 UTC by KarinaMendez2

for: https://github.com/openstax/cnx-recipes/issues/3801

2021-04-28 21:50 UTC, LostMojo commented
The travis tests are failing and I suspect that's to do with the styleguides-- I think you'll have to get rid of the references to them in _config before you're able to merge

2021-04-29 16:51 UTC, KarinaMendez2 commented
Currently working:

General things:
- [ ] Table of Contents - Documentation #2060 / Working card: #3804
- [ ] Splash image - Documentation #1752 / Working card: #3806
- [ ]  Figure and table caption/title/number styling - Documentation #2185 / Working card: #3807
- [ ]  Headers - Documentation #2144 / Working card: #3805
- [ ]  Chapter Outline & Introduction - Documentation #2189 / Working card: #3817
- [ ]  Learning Objectives - Documentation #2190 / Working card: #3818
- [ ]  Tables - Documentation #2204 / Working card: #3819
- [ ] Examples with titles - Documentation #2209 / Working card #3821
- [ ] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

Feature-like things:

- [ ] no class notes - Definition & Formulas - Documentation #2191 / Working Card #3820
- [ ]  Work It Out - Documentation #2256 / Working Card #3830

End of Section Content - Documentation #2463 / Working Card #3831

- [ ] Check Your Understanding
- [ ]  Exercises

2021-04-29 18:41 UTC, kswanson33 requested changes
This is looking really good overall! I can't speak much to the recipe work, but the styles work is coming along great.

- A couple comments mostly regarding making sure the PR description matches what features are getting added in this PR. 
- I also noticed the PR description says something about a Check Your Understanding feature being added, but I don't see this in the implementation
- It looks like specs are now failing due to the generated output of the recipe differing from the actual output on those `intro-body` lines that we were able to generate with the `build-recipes` script but not the `node` script. (I don't know why the build can't just ... generate the file for us. 🤦) If that script still isn't working for you I'd uhhhhh maybe just manually copy those lines into the recipe file. For Now. 😬 😬 
- Travis is also complaining about something in the manifest.json. I truly don't know anything about this.

2021-04-29 18:41 UTC, kswanson33 commented on styles/books/contemporary-math/book.scss
> +      color: black,
Instead of using the value `black` directly, it's better to use a color from `colorMap`

2021-04-29 18:41 UTC, kswanson33 commented on styles/books/contemporary-math/book.scss
> +@include use('ReviewExercises', 'corn:::OneColumnExercisesModuleShape');
Are these finished? If so, they can be added as features in the PR description. If not, it's better to take them out and put them in the next one.

2021-04-29 18:41 UTC, kswanson33 commented on styles/books/contemporary-math/book.scss
> +  OneColumnModuleExercises: (
This is a little thing, but it would be more descriptive to call this `SectionExercises` instead of naming the settings after the shape.

2021-04-29 18:41 UTC, kswanson33 commented on styles/books/contemporary-math/book.scss
> +@include use('Index', 'corn:::IndexShape');
Same with these as above -- if finished, add these features in the PR description. If not finished, take them out and add them in a later PR.

2021-04-29 18:44 UTC, kswanson33 commented
Almost forgot -- the base branch should be the current milestone, not master. We don't merge anything directly into master in this repo except the milestones themselves on the 2-week release schedule.

2021-05-03 14:08 UTC, LostMojo commented
(Also! The current release is the branch that usually follows the pattern of (adjective starting with letter).(city name starting with the same letter). I _think_ we're on g, so that's... gilded.gza, I think?

2021-05-03 19:49 UTC, lwtchu commented
:eyes: i think we're on incandescent incheon

2021-05-17 00:17 UTC, closed without merging

2021-05-17 00:17 UTC, KarinaMendez2 commented
continued on new PR: https://github.com/openstax/cnx-recipes/pull/3850