Update books.txt
openstax/cnx-recipes pull request #3871
Opened 2021-05-20 14:27 UTC by lwtchu

update with production link and added new titles (coreq college alg, sociology 3e and IP)

2021-05-20 17:02 UTC, Stackblocks requested changes

2021-05-20 17:02 UTC, Stackblocks commented on books.txt
> +  "accounting-vol-2           accounting                         920d1c8a-606c-4888-bfd4-d1ee27ce1795   col67941   cnx.org               mixins/                    cardboard"
This colID 404s, should it be col25479?

2021-05-21 20:35 UTC, Stackblocks approved these changes

2021-05-21 20:36 UTC, Stackblocks commented
We may want to ask someone who knows about how robots interface with this about whether or not the tests exploding is expected. If something was dependent on the old books.txt that'll need to be changed as well (and probably shouldn't be that closely tied to it).

2021-05-24 14:52 UTC, lwtchu commented
@brittany-johnson :eyes: will help me because it's exploding

2021-06-03 19:50 UTC, merged