poli sci - Remove iframes & adjust figure margins
openstax/cnx-recipes pull request #3942
Opened 2021-06-22 16:39 UTC by kswanson33

Figure margin adjusted to allow for more space above the figure:

Original: 
![image](https://user-images.githubusercontent.com/26280712/122965841-a5f6df80-d356-11eb-95d7-c3b3a7446588.png)

Now:
![image](https://user-images.githubusercontent.com/26280712/122965872-b14a0b00-d356-11eb-8e49-60fa3c4484ed.png)

Styles have been rebuilt.

2021-06-22 19:12 UTC, brittany-johnson commented on styles/designs/cosmos/parts/_figureimage-components.scss
> +        margin-top: 1rem,
since this affects a few books prob want to let alan know in the card to check figures in the styles affected?

2021-06-22 19:12 UTC, brittany-johnson approved these changes

2021-06-25 10:28 UTC, wilkus27 requested changes

2021-06-25 10:28 UTC, wilkus27 commented on styles/designs/cosmos/parts/_figureimage-components.scss
> +        margin-top: 1rem,
I'm not sure if we should add margin to all figures. There is no space between figure and subtitle, because we set margin-bottom to 0 for this component:

![image](https://user-images.githubusercontent.com/40228854/123411063-51e73780-d5b0-11eb-8c26-2e7f3ebb0839.png)

How about making this property for figure `OPTIONAL` and enable it only for iconned notes?

Or we can create new component for figure right after subtitle. Actually we don't need margin top for figures that are e.g. after para in the note.

2021-06-30 15:59 UTC, kswanson33 commented on styles/designs/cosmos/parts/_figureimage-components.scss
> +        margin-top: 1rem,
Thanks! I changed the implementation, let me know what you think!

2021-07-01 11:49 UTC, wilkus27 approved these changes
Everything looks good :relaxed:

2021-07-05 14:27 UTC, LostMojo approved these changes

2021-07-06 14:01 UTC, merged