Issue 3924 Annotation Text
openstax/cnx-recipes pull request #3951
Opened 2021-06-24 23:11 UTC by LostMojo

For issue #3924

2021-06-25 11:14 UTC, ajluk reviewed
I just left a suggestion about changing Annotation Text component name.

2021-06-25 11:14 UTC, ajluk commented on styles/books/english-composition/book.scss
> +    'AnnotationText:::font-family': (_ref: 'typography:::titleOption2Font'),
@LostMojo Everything looks good. I have only one suggestion to change the name of the `AnnotationText` component a little, maybe to InnerAnnotatationText or something similar, because there is a shape of the same name (see line 62 above) and this can be confusing.

2021-06-25 11:21 UTC, wilkus27 requested changes

2021-06-25 11:21 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +@include use('PublicDomainText', 'cosmos:::PublicDomainShape');
I noticed that `AnnotationTextShape` and `PublicDomainTextShape` are created in common file by BrittneyJ:

![image](https://user-images.githubusercontent.com/40228854/123415316-5e21c380-d5b5-11eb-83fe-0df243b4e00c.png)

They are added only to english composition for now, but I understand they will be used in other themes (different then cosmos) as well. Am I right @brittany-johnson ?

If yes, I think we should keep all components in common file. Also maybe we should use `AnnotationText` name everywhere? I mean, here are components from common-components file:

![image](https://user-images.githubusercontent.com/40228854/123416386-c58c4300-d5b6-11eb-83c7-4e8076d61bc6.png)

What do you think to rename first one to `AnnotationText__Container` and second one to `AnnotationText--WithLeftBorder__Container` and apply to it these properties:

![image](https://user-images.githubusercontent.com/40228854/123416592-0c7a3880-d5b7-11eb-81fc-fd9afa39b9e2.png)

Then we can use one shape both for Public Domain and StudentSample (e.g `AnnotationTextWithLeftBorderShape`).

Also this component:

![image](https://user-images.githubusercontent.com/40228854/123417133-af32b700-d5b7-11eb-84d1-f4204d1afd8e.png)

we can rename to `AnnotationText--WithLeftBorder__Content`. What do you think? :slightly_smiling_face:

2021-06-25 11:23 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +    'AnnotationText:::font-family': (_ref: 'typography:::titleOption2Font'),
@ajluk we did a review at the same time :smile: In this case, can you look at mine comments and tell what do you think about it?

2021-06-25 11:37 UTC, ajluk commented on styles/books/english-composition/book.scss
> +    'AnnotationText:::font-family': (_ref: 'typography:::titleOption2Font'),
@wilkus27 It seems so :smile: I agree that we can standardize the components properties and make one shape (AnnotationTextWithLeftBorderShape).

2021-06-25 16:58 UTC, LostMojo commented on styles/books/english-composition/book.scss
> +@include use('PublicDomainText', 'cosmos:::PublicDomainShape');
That sounds great! I think I also have a way to condense the shape a little

2021-06-25 17:13 UTC, LostMojo commented on styles/books/english-composition/book.scss
> +@include use('PublicDomainText', 'cosmos:::PublicDomainShape');
Done! Both .public-domain and .student-samples can use the same shape now

2021-06-28 10:29 UTC, wilkus27 approved these changes

2021-06-28 14:10 UTC, merged