Pdf spanish translation
openstax/cnx-recipes pull request #3970
Opened 2021-06-30 14:52 UTC by KarinaMendez2

for: https://github.com/openstax/cnx-recipes/issues/3959#issuecomment-871004812

2021-07-01 12:36 UTC, wilkus27 commented on styles/designs/cardboard/pdf/locale/es/_folio.scss
> +  }
It's not related with this PR, but I noticed that in every folio file this mixin is named `CornFolioStyles`. We should probably create a separate card for that and fixed names to fit to the theme.

2021-07-01 12:49 UTC, wilkus27 requested changes
I added some comments. Beside that, should this be applied now to any specific book? If yes, you have to add import to `book.scss` file for this book.

Here is an example of Polish Psychology:

![image](https://user-images.githubusercontent.com/40228854/124126919-71340800-da7b-11eb-9142-2151bbd8a4e4.png)

2021-07-01 12:49 UTC, wilkus27 commented on styles/designs/corn/pdf/locale/en/_folio.scss
> +@import '../pdf/locale/pl/text-varaibles';
I think we can remove this import. From polish file too. I gues that is something from previous idea how to translate words :thinking: I don't know. As I checked file `text-variables` doesn't exist, so it shouldn't change enything.

Also I noticed that your directory of this file is named `en`, not `es`.

2021-07-01 12:49 UTC, wilkus27 commented on styles/designs/cosmos/pdf/locale/en/_folio.scss
> +//Folio content strings
Here also directory is `en`. It should be `es`.

2021-07-28 15:10 UTC, brittany-johnson requested changes

2021-07-28 15:10 UTC, brittany-johnson commented on styles/books/u-physics/book.scss
> +@import '../../designs/carnival/pdf/locale/es/folio';
Changing this path will make the English folio Spanish - I'm wondering if there's a way we can import the folio conditionally so that we don't have to create a whole new book.scss just for the Spanish translation? @wilkus27 

@KarinaMendez2 In the Spanish content, is there something in the `head` element of the document that specifies the language?

2021-07-29 11:15 UTC, wilkus27 commented on styles/books/u-physics/book.scss
> +@import '../../designs/carnival/pdf/locale/es/folio';
Hmm good question :thinking: When we created such solution with @ajluk we assumed that all foreign books will have separate recipes (as Polish books). I saw you had a call with Phil about it. Do you came up with any ideas?

2021-08-02 18:29 UTC, LostMojo approved these changes

2021-08-03 09:33 UTC, wilkus27 commented on styles/designs/carnival/pdf/_folio.scss
> +[data-pdf-folio-preface-message][data-pdf-folio-access-message] {
I have a few questions :relaxed: These are new attributes, that's right? Where are they added? In the content?
I'm asking because changes from this PR have an impact on all books from carnival and corn theme. And if books don't have these attributes folio for them will be broken.

As I see there is output file only for u-physics. Did you use `./script/build-styles` command or the short one that builds styles only for one specific book?

2021-08-03 09:44 UTC, wilkus27 requested changes

2021-08-03 09:44 UTC, wilkus27 commented on styles/designs/carnival/pdf/_folio.scss
> +[data-pdf-folio-preface-message][data-pdf-folio-access-message] {
Ok I looked to the Kitchen PR https://github.com/openstax/kitchen/pull/341/files :grin: They are added here:

![image](https://user-images.githubusercontent.com/40228854/127993788-c06a0548-e8d4-48be-a286-78c152f16555.png)

But as I understand it will be implemented only to u-physics for now, so other books won't have these attributes. We can resolve that in two ways: either we have to add attributes to books in old recipe or we have to create some condition when folio should use old settings and when the new ones.

2021-08-03 10:12 UTC, wilkus27 commented on styles/designs/carnival/pdf/_folio.scss
> +[data-pdf-folio-preface-message][data-pdf-folio-access-message] {
Maybe we can add such variable to `book.scss` file:

![image](https://user-images.githubusercontent.com/40228854/127997149-53bd4368-1d86-4227-b81d-939bc14490e4.png)

And then in folio:

```
@if $useNewRecipe == true {
   $prefaceContent: string(preface-msg);
   $accessContent: string(access-for-free-msg);

   [data-pdf-folio-preface-message][data-pdf-folio-access-message] {
     string-set: preface-msg attr(data-pdf-folio-preface-message) access-for-free-msg attr(data-pdf-folio-access-message); }
} else {
  $prefaceContent: "Preface";
  $accessContent: "Access for free at openstax.org.";
}
```

But with this solution after we add such variable to `book.scss` file we can't generate PDF from file baked with old recipe. Otherwise folio will be broken. The question is are we ok with that :thinking: If we want to be able to generate PDFs from files baked both with old and new recipe, I think we should create mixin which adds attributes to all books.

@KarinaMendez2 @ajluk @kswanson33 I'm curious what is your opinion about that. Let me know what do you think :wink: Which solution will be better? Or maybe you have some other ideas.

2021-08-03 14:38 UTC, wilkus27 approved these changes
Decision: books will not be released without Kitchen recipe, so we are ok that folio is broken for books baked with old pipline.

2021-08-04 18:20 UTC, merged

2021-08-06 22:21 UTC, lwtchu commented
CONGRATULATIONS :) i know this was a lot of work nice nice nice nice