Change Anthro learning objectives to Carnival
openstax/cnx-recipes pull request #3975
Opened 2021-07-06 18:28 UTC by LostMojo

First part of switching Anthropology over to Carnival (and changing carnival to better match its specs #1077 )

This may affect other books in carnival

2021-07-06 19:25 UTC, lwtchu commented
@Stackblocks for testing i think we can focus these changes on anthro, uni physics and anatomy & physiology since they're the next books up in q3 to publish  🤔

2021-07-08 12:25 UTC, wilkus27 requested changes

2021-07-08 12:25 UTC, wilkus27 commented on styles/books/anthropology/book.scss
> +
I think we should remove from this file everything related with cosmos theme and just add carnivals styles for elements one by one. I'm afraid that some of the settings might be overwritten when we have imports from both themes.

2021-07-08 20:57 UTC, kswanson33 approved these changes
This seems like a reasonable approach to me.

Don't forget to base this on the milestone!

2021-07-08 21:41 UTC, LostMojo commented on styles/books/anthropology/book.scss
> +
Done! I've left some of the old Cosmos commented out, so we can see at a glance the classes & structure used

2021-07-09 06:42 UTC, wilkus27 approved these changes

2021-07-09 13:21 UTC, wilkus27 commented on styles/books/anthropology/book.scss
> +// @include use('LearningObjectives', 'carnival:::LearningObjectivesShape');
This should be uncommented :wink:

2021-07-09 13:27 UTC, wilkus27 commented on styles/books/anthropology/book.scss
> +// @include use('BookRoot', "common:::BookRoot");
This one too :upside_down_face:

2021-07-09 14:30 UTC, merged