style figures and tables in carnival for anthropology
openstax/cnx-recipes pull request #3981
Opened 2021-07-09 18:40 UTC by kswanson33

#3962 & #3963

![image](https://user-images.githubusercontent.com/26280712/125122452-73254900-e0c3-11eb-93bd-5974ae22ab3b.png)

![image](https://user-images.githubusercontent.com/26280712/125122505-8506ec00-e0c3-11eb-8ccb-743bf73c91cc.png)

2021-07-12 13:32 UTC, ajluk requested changes

2021-07-12 13:32 UTC, ajluk commented on styles/designs/carnival/parts/_caption-components.scss
> +        color: enum('ValueSet:::OPTIONAL'),
@kswanson33 Can I ask why this property value is set to `optional`? As far as I remember all the tables/figures captions should rather be unified through the whole theme. If yes Fake Titled Tables should also have the captions titles colorized and the value should be set to `required`. But let me know if I'm wrong :slightly_smiling_face:

2021-07-12 13:32 UTC, ajluk commented on styles/designs/carnival/parts/_caption-components.scss
> +        color: enum('ValueSet:::OPTIONAL'),
See the comment from above.

2021-07-12 14:12 UTC, ajluk commented
@kswanson33 I've got also one more question about colored table bottom borders, because they are included in the documentation but you don't add them within this PR? Was it intended? There was a problem with such borders in carnival in the past, but in cosmos theme Natalia figured out how to fix it. Here is the PR with such solution in cosmos: https://github.com/openstax/cnx-recipes/pull/3731/files

2021-07-12 14:48 UTC, LostMojo approved these changes

2021-07-12 16:56 UTC, kswanson33 commented
@ajluk Thank you for catching all that! You're right, I had just overlooked the content-driven alignment, bottom border color, and also the top border, all of which I've now added. I wasn't sure if it was okay to impact `FakeTitleTables` with the caption color, but I've gone ahead and made that change since I agree it's probably what we want.

2021-07-13 07:50 UTC, ajluk commented on styles/design-settings/carnival/parts/_table-settings.scss
> +        LastTableRowData: (
@kswanson33 The color bottom border was added to last `td`s in this way in carnival theme previously but not worked for merged cells. I think the only solution is to use `after` element added as Natalia did in cosmos in the PR I pasted above: https://github.com/openstax/cnx-recipes/pull/3731/files. Here is the after element Natalia used in the table shapes to create a bottom border: 
![image](https://user-images.githubusercontent.com/55203598/125412056-d6162900-e3be-11eb-892c-41874bb5a802.png) and then she used in in the caption container instead of `td`: 
![image](https://user-images.githubusercontent.com/55203598/125412272-078ef480-e3bf-11eb-855f-0112173f6949.png)
I hope it's not confusing, but if you will have some questions just let me know :) I have also asked about it Larissa yesterday because I was confused myself if we need such changes in carnival because previously we decided to remove the bottom stroke there and wasn't sure if you discussed it and my comment were just irrelevant :sweat_smile:

2021-07-13 08:21 UTC, ajluk requested changes
I have left some more comments in the places which concerned me and also asked Larissa for advise how much wide the changes should be, because I'm not sure here as well :)

2021-07-13 08:21 UTC, ajluk commented on styles/design-settings/carnival/parts/_table-settings.scss
> +            border-bottom-color: (_ref:"colorMap:::figureNumberColor"),
@kswanson33 Also this color should match the accent color for athropology spec: 
![image](https://user-images.githubusercontent.com/55203598/125414457-35259d67-7784-4c66-b1ac-d780aeb41498.png)
It is also a book specific color: 
![image](https://user-images.githubusercontent.com/55203598/125414680-82ce6eba-d9ee-4792-b5bc-987e86bde721.png)
It should be set in the settings in anthropology `book.scss` file. And here we need Larissa advise I guess, because I'm not sure if the book specific colors for bottom strokes should be set for every carnival book or just for anthropology for now. If you don't want to do that within this PR maybe we can set the `border-bottom color` property value to `OPTIONAL` temporarily and set the value only for anthropology. And then create a separate PR adding strokes for the rest of the carnival books.

2021-07-13 08:21 UTC, ajluk commented on styles/design-settings/carnival/parts/_table-settings.scss
> +            border-bottom-color: (_ref:"colorMap:::figureNumberColor"),
I have asked Larissa if the change should be made just for anthropology here: https://github.com/openstax/cnx-recipes/issues/1080#issuecomment-878879358

2021-07-13 14:30 UTC, kswanson33 commented on styles/design-settings/carnival/parts/_table-settings.scss
> +            border-bottom-color: (_ref:"colorMap:::figureNumberColor"),
In a PM with Larissa, we decided to change the accent color to red instead of blue -- I should have documented that publicly, apologies! I've added a comment to the [documentation](https://github.com/openstax/cnx-recipes/issues/3963#issuecomment-879135506). Sounds like Larissa wants to move towards keeping things like accent colors the same across the theme.

2021-07-13 14:43 UTC, kswanson33 commented on styles/design-settings/carnival/parts/_table-settings.scss
> +        LastTableRowData: (
I see 👀, my bad for trying to implement this without looking at that PR! Thank you for pointing out this bug, good to know. I will go back and implement this the cosmos way.

2021-07-13 15:48 UTC, ajluk commented on styles/design-settings/carnival/parts/_table-settings.scss
> +            border-bottom-color: (_ref:"colorMap:::figureNumberColor"),
Oh, ok. Thank you for the explanation. I wasn't aware that such things will be unified. :smile:

2021-07-14 15:44 UTC, ajluk requested changes
@kswanson33 There is only one thing I think should be updated with your recent changes (Fake Titled Tables shape), but please correct me if I missed something.

2021-07-14 15:44 UTC, ajluk commented on styles/designs/carnival/parts/_table-shapes.scss
> +                        $Table__BottomBorder,
@kswanson33 As I understood from documentation guess this component should be added also to Fake Titled Tables shape below. This also requires testing a carnival book containing Fake Title Tables.

2021-07-14 16:34 UTC, ajluk commented on styles/designs/carnival/parts/_table-shapes.scss
> +                        $Table__BottomBorder,
@kswanson33 As we discussed slack adding a bottom border to Fake Title Tables will be done later on within a separate issue and PR.

2021-07-14 16:35 UTC, ajluk approved these changes

2021-07-14 16:52 UTC, merged