style splash and chapter objectives for anthropology
openstax/cnx-recipes pull request #3983
Opened 2021-07-09 22:45 UTC by kswanson33

will resolve #3961, #3965, and #3957

![image](https://user-images.githubusercontent.com/26280712/125142384-982ab380-e0e5-11eb-9763-f1cfdea04f05.png)

2021-07-12 14:44 UTC, LostMojo approved these changes
Looks good! Thank you for doing this!

2021-07-13 12:39 UTC, ajluk requested changes
@kswanson33 I have left some comments where I'm little concerned about how this changes affect other books in carnival.

2021-07-13 12:39 UTC, ajluk commented on styles/books/anthropology/book.scss
> +    'OutlineFullWidthTitleBottomBorder:::border-bottom-color': (_ref: 'colorMap:::chapterOutlineColor'),
@kswanson33 This property set for `OutlineFullWidthTitleBottomBorder` from above can be removed since this component no longer exists. But I'm little concerned because this change (I mean removing the component and restyle chapter outline) affects every book in carnival theme, is it intended? If yes this property should be removed from other carnival `book.scss` files as well. If this change only should affect anthropology we need to create a separate shape for Chapter Outline for this book not containing `OutlineFullWidthTitleBottomBorder` and keep OutlineFullWidthTitleBottomBorder (`$ChapterOutline--FullWidth__Title--BottomBorder: titleBottomBorder("OutlineFullWidth", 116.7); from line 103 `component in the `chapter-intro-components` file.

2021-07-13 12:39 UTC, ajluk commented on styles/designs/carnival/parts/_chapterintro-components.scss
> +
Could you add `--Margin` to the components name  because now it is only used in in the Chapter Intro Margin Shape and change the `padding-right` property  to `REQUIRED`? Or maybe a better idea could be to just leave a comment that if change the styling of the full width chapter intro will be permanent the change of the name and property value will be needed there? What do you think? :slightly_smiling_face:

2021-07-13 15:48 UTC, kswanson33 commented
@ajluk thanks for pointing this out, I've removed the `OutlineFullWidthTitleBottomBorder` & renamed the `ChapterOutline--Margin__Objective`, and rebuilt styles to make sure everything still works (no changes). & I can confirm that this should impact the rest of the carnival theme (many of these anthropology issues seem to include some carnival refactoring)

2021-07-13 15:54 UTC, ajluk approved these changes

2021-07-13 15:58 UTC, merged