Add Anthro Feature Boxes
openstax/cnx-recipes pull request #3984
Opened 2021-07-12 14:16 UTC by LostMojo

#3967

2021-07-12 17:33 UTC, kswanson33 requested changes

2021-07-12 17:33 UTC, kswanson33 commented on styles/books/anthropology/book.scss
> -
Since this is commented out, it should probably just be removed, right?

2021-07-12 17:33 UTC, kswanson33 commented on styles/designs/carnival/parts/notes/_notes-components.scss
> +    font-weight: 900,
will this change impact other carnival books/do their styles need to be recompiled?

2021-07-13 09:04 UTC, ajluk approved these changes
@LostMojo Looks good besides the things that Kendra already pointed!

2021-07-13 16:05 UTC, LostMojo commented on styles/designs/carnival/parts/notes/_notes-components.scss
> +    font-weight: 900,
It will, but Larissa wants the old ones updated to match the new specs-- CSS has been recompiled

2021-07-16 17:16 UTC, kswanson33 approved these changes

2021-07-16 19:00 UTC, merged