(WIP) Move generic styles from rex into a seperate theme
openstax/cnx-recipes pull request #4057
Opened 2021-08-12 15:29 UTC by jarosik10

2021-08-16 15:24 UTC, wilkus27 requested changes
Looks good :wink: :+1: I have just a few requested changes.

2021-08-16 15:24 UTC, wilkus27 commented on styles/designs/webview/parts/_titles-shapes.scss
> +                $H6,
You probably should add section wrappers to all titles shapes:

![image](https://user-images.githubusercontent.com/40228854/129587372-71898631-a579-448a-988c-23034c59576b.png)

They are necessary, because some elements have headers (e.g notes have h3) and they are styled differently then page titles. When we specify precise selector (e.g for `section > section > section > h3`) we are sure that other styles are not overwritten (e.g for `[data-type="note"] > h3`).

2021-08-24 14:37 UTC, jarosik10 commented
@wilkus27 @ajluk 
What would be a proper solution to handle more than one selector inside `_subselector`?
Creating another component?
for example;
from:
```css
$Media--InFigure: (
  _name: "MediaInFigure",
  _subselector: ' > [data-type="media"], > .media',
  _properties: (
    display: block,
    margin: 0,
    text-align: center,
  )
);
```
to:
```css
$Media--InFigure: (
  _name: "MediaInFigure",
  _subselector: ' > [data-type="media"]',
  _properties: (
    display: block,
    margin: 0,
    text-align: center,
  )
);

$Media--InFigure2: (
  _name: "MediaInFigure",
  _subselector: ' > .media',
  _properties: (
    display: block,
    margin: 0,
    text-align: center,
  )
);
```
It doesn't look good to me, because of the code repetition. Do you have any other idea?

2021-08-30 15:37 UTC, jarosik10 commented
@TomWoodward 
Fixes:

1. Bigger font-size
2. Some of the styles in rex seems to be always overridden/dead. Omitting these selectors would make the styling of some of the cnx-recipies components simpler.

Todo:
Disable default list-style in abstract

1. Change font weight of terms
2. Missing styles for glossary/eoc/eob
3. Add styling for noteish elements. Should I create a shared components for noteish elements? Or make every noteish element to be represented by an individual set of components? The answer to this question depends on how much do we want every noteish element to be customizable and what styling properties we would like to inject from the pdf styles.
4. Check how much the pdf styles for noteish elements differ depending on book design.

I think it’d be good to create some basic shared styling for noteish elements. And even before completing the styles migration from rex to cnx-recipes, i would like to test the injection of book specific styles (from a different design) into the existing styles of webview design. It would check if the existing conception, and already created shapes actually work. For example, it could show me that some properties should be changed to optional, or should not be hardcoded, etc.

2021-08-31 15:37 UTC, jarosik10 commented
> Bigger font-size

Every style needs a container. In rex it is nested inside:
```css
#main-content:not([data-dynamic-style="true"]), .content-excerpt:not([data-dynamic-style="true"]) {
  font-size: 1.6rem;
  line-height: 2.3rem;
}
```
in cnx-recipies we do not have such a container.

2021-09-13 13:51 UTC, wilkus27 requested changes
It looks very good :relaxed: I found a few small things related to names of components. Beside that everything is ok :tada:  I added also a comment for other developers, so they will know what are the plans and why some things are created differently then in styles for PDFs. 

Also I have one question: there are no output files in this PR. I know you are just generating them locally and use them somehow in a rex. Are we ok with that for now? Or it will be better to push these files here so everyone has access to them?

One of the next step will be also to modify `build-styles` and `build.js` scripts so they can generate files for webview styles properly.

2021-09-13 13:51 UTC, wilkus27 commented on styles/designs/webview/parts/_caption-components.scss
> +);
These two components have the same `_name`.  They should be different.

2021-09-13 13:51 UTC, wilkus27 commented on styles/designs/webview/parts/_figureimage-shapes.scss
> +        )),
### Information for other developers

First step of moving rex styles to Baked Styles project was to get final css file the same as this one from Rex project. Because of that we decided to make some simplifications. As we can see here, this shape doesn't have one parent component. There are a few components at the same level:

![image (11)](https://user-images.githubusercontent.com/40228854/133089793-8afb4939-2674-4cb6-b601-0c597c4a0a71.png)

For that reason there are no selectors in settings:

![image (12)](https://user-images.githubusercontent.com/40228854/133090107-850ea778-f37e-4197-b1af-7c0b8d0a875a.png)

For now it's working but in the next step, when we'll know what is the final design for webview, it should be refactored.

#### To do in the fure
- move settings to their own files (e.g. settings for figures should be in file `figure-settings.scss`)
- split shapes in a way that each of them has one parent component and its selector is defined in settings
- investigate that we need all of the selectors 

For example:
![image (13)](https://user-images.githubusercontent.com/40228854/133091481-45eccc9e-184a-4600-b2d3-2a50f4e92c30.png)

Here we need to check if these are two different elements or maybe this is one element that has two attributes, so we can use just one of them for styles. Also there might be media that has class, but doesn't have data-type etc. We should check all cases, then rename those components in a descriptive way.

2021-09-13 13:51 UTC, wilkus27 commented on styles/designs/webview/parts/_titles-components.scss
> +  _name:"H3Title",
Typo :wink: It should be `H5Title`

2021-09-13 13:51 UTC, wilkus27 commented on styles/designs/webview/parts/_titles-components.scss
> +  _name:"H3Title",
Also here. `H6Title`

2021-09-15 12:15 UTC, wilkus27 approved these changes

2021-09-15 12:57 UTC, merged