Add noteish elements
openstax/cnx-recipes pull request #4110
Opened 2021-09-15 14:52 UTC by jarosik10

css file is uploaded: https://jarosik10.github.io/rex-test-styles/add-noteish-elements/webview-generic.css
Testing was described: #4105

2021-09-22 09:02 UTC, wilkus27 requested changes
I left a few comments. If they start with :memo: **To do** it means that this is something that can be done later in next step of refactoring. But if you feel it's easier to do some of this things now, feel free to do that :wink: All other comments are requested changes for this PR. Let me know if you have any questions :relaxed:

2021-09-22 10:23 UTC, ajluk reviewed
I just left some comments here and there, but these are just thoughts, let me know what do you think. :slightly_smiling_face:

2021-09-22 10:23 UTC, ajluk commented on styles/designs/webview/parts/_notes-components.scss
> +);
@wilkus27 Your suggestion here makes me wonder if we should also move at this point titles components to separate `_titles-components.scss` file from notes and exercises components? cc @jarosik10 :thinking:

2021-09-22 10:23 UTC, ajluk commented on styles/books/generic/webview.scss
> +        _selectors: ('[data-type="note"]', '.note', '[data-type="example"]', '.example'),
@wilkus27 I agree, maybe a good name for such elements could be just `FeaturesShape`? :thinking:

2021-09-22 10:23 UTC, ajluk commented on styles/designs/webview/parts/_exercise-components.scss
> +$Exercise__Problem1: (
@wilkus27 @jarosik10 Do you think it could be useful to change the naming convention from components like `Problem1`, `Problem2` etc. to something more descriptive like f.ex: `Problem--Attr`, `Problem--Class`?

2021-09-22 11:05 UTC, wilkus27 commented on styles/designs/webview/parts/_exercise-components.scss
> +$Exercise__Problem1: (
In the next step we are going to investigate which selectors are actually used in markup and probably lots of them will be removed, so I think we can use 1,2,3 etc. for now :thinking: But this is something that definitelly should be cleaned up later, so I'll put this to :memo: **To do**.

2021-09-22 11:16 UTC, wilkus27 commented on styles/designs/webview/parts/_notes-components.scss
> +);
Hmm :thinking: There is a lots of titles here. I think for PDFs we moved titles to `titles-components` file when there was one specific title of the element, e.g Learning Objectives title. In PDFs notes titles are styled in many different ways and they're styles depends on properties of other elements (e.g. icons) so it's easier to keep everything in one place rather then jumping between files when you're making some changes in the future.

We still don't know what is the final design. I think we should come back to this later, in the next step. What do you think? I can put this on :memo: **To do** list.

2021-09-22 13:51 UTC, ajluk commented on styles/designs/webview/parts/_notes-components.scss
> +);
Yes, there is a lot of titles and they can vary later especially for the notes if the design will include different styling for titles in notes. Let's put this on :memo: **To do** list. We can decide later where to keep them. :+1:

2021-09-22 14:41 UTC, jarosik10 commented on styles/designs/webview/parts/_exercise-components.scss
> +  _subselector: (' > .ui-toggle-wrapper > button.ui-toggle::before'),
It's not so easy ^^ It's all about the different states of the parent element. For example:
`.solution`
`.solution:not(.ui-solution-visible)`
`.solution.ui-solution-visible`

Nesting `$Exercise__Solution__Toggle--Visible` inside `$Exercise__Solution__Toggle__Wrapper` would add unnecessary additional css styles and it make the shape biggerr.

I understand your concern and I think that we should mark it as :memo: **to do** and think about it later.

2021-09-22 14:43 UTC, jarosik10 commented on styles/designs/webview/parts/_exercise-components.scss
> +  _subselector: (' [data-type="problem"]::before'),
Similar problem with parent elements:
`.example`
`.example.problems-exercises`

2021-09-22 14:44 UTC, wilkus27 commented on styles/designs/webview/parts/_exercise-components.scss
> +  _subselector: (' > .ui-toggle-wrapper > button.ui-toggle::before'),
### EDIT: :memo: To do:

We are moving this to to do list.
Styles in REX are built in this way. Selector `> .ui-toggle-wrapper` has property ` text-align: center` only as a child od `data-type="solution"`, not as a child of solution with `.ui-solution-visible`. Without investigating this we can't say for sure that it's not done for a purpose. We should look at this in the next step.

2021-09-22 15:14 UTC, jarosik10 commented on styles/designs/webview/parts/_conceptualQuestions-components.scss
> +);
I've found conceptual questions here https://rex-web.herokuapp.com/books/college-physics/pages/1-conceptual-questions.
But the `.conceptual-question` there is not a class of examples.
I'd prefer to wait for the Phil's tool to find more places where this selector is used and the decide how to name this shape.

2021-09-23 08:30 UTC, wilkus27 approved these changes

2021-09-23 13:01 UTC, merged