Add additional list styles
openstax/cnx-recipes pull request #4135
Opened 2021-09-24 15:37 UTC by jarosik10

2021-09-27 18:22 UTC, wilkus27 requested changes

2021-09-27 18:22 UTC, wilkus27 commented on styles/designs/webview/parts/_lists-components.scss
> +$UnorderedList--InAbstractClass--After: (
Can you rename this to `$UnorderedList--InAbstractClass__After`? :upside_down_face: `--` we use for type of some element (`InAbstractClass` is a type of `UnorderedList`), and `__` for new element (`::after` is a child of `UnorderedList`).

2021-09-27 18:22 UTC, wilkus27 commented on styles/designs/webview/parts/_lists-components.scss
> +);
### :memo: To do:

Check where `.list` and `[data-type="list"]` are used. Maybe we can combine `ListStructureShape` with `ListsShape`.

2021-09-27 18:22 UTC, wilkus27 commented on styles/designs/webview/parts/_lists-components.scss
> +);
What do you think to rename this to `$UnorderedList--Unstyled`? Maybe we can reuse this component in other places based on its style.

2021-09-27 18:22 UTC, wilkus27 commented on styles/designs/webview/parts/_lists-components.scss
> +);
I think this is rather list item then list of some level :thinking:

2021-09-27 18:22 UTC, wilkus27 commented on styles/output/webview-generic.css
> +  list-style-type: none; }
Are we sure we want to unstyle all unnumbered lists in Preface? :thinking:

2021-09-27 19:08 UTC, ajluk reviewed
I just left one comment. Natalia has already commented put everything else. :slightly_smiling_face:

2021-09-28 13:05 UTC, jarosik10 commented on styles/designs/webview/parts/_learning-components.scss
> +    background-color: enum('ValueSet:::REQUIRED'), //ededed
Oops, that was my cheat sheet for the color :D I'll remove it.

2021-09-28 13:09 UTC, jarosik10 commented on styles/output/webview-generic.css
> +  list-style-type: none; }
Well.. this is how is it styled in rex.

2021-09-28 13:33 UTC, jarosik10 commented on styles/designs/webview/parts/_lists-components.scss
> +);
@wilkus27 
These are the styles from rex:
```css
.stepwise {
  list-style-type: none;
  padding-left: 0;
  > li {
    display: flex;
    .os-stepwise-token {
      white-space: pre;
    }
    .os-stepwise-content {
      > ul, ol {                 <--- there is a second level
        padding-left: 1rem;
      }
    }
  }
}
```
I agree that `StepwiseList__FirstLevel` should be renamed to `StepwiseList__ListItem`, but because of that nested `ul` and `ol` inside `li`, the names: `$StepwiseList__SecondLevel--UnorderedList`, `$StepwiseList__SecondLevel--OrderedList` are okay, right??

2021-09-28 13:44 UTC, jarosik10 commented on styles/designs/webview/parts/_lists-components.scss
> +$StepwiseList__SecondLevel--OrderedList: (
@ajluk @wilkus27 
Could it be `$StepwiseList__NestedList--UnorderedList`? What do you think?

2021-09-29 06:40 UTC, wilkus27 approved these changes
Looks good! :wink: :+1:

2021-09-29 11:47 UTC, merged