create section workscited shape
openstax/cnx-recipes pull request #4141
Opened 2021-09-30 12:30 UTC by ajluk

For: #4118

2021-10-04 19:23 UTC, kswanson33 requested changes
looks good except for typo! :)

2021-10-04 19:23 UTC, kswanson33 commented on styles/designs/cosmos/parts/_section-workscited-components.scss
> +    _name: "ParagraphhWithIndentation",
typo in 'paragraph' here; spelled 'paragraphh' -- also present in the shape file

2021-10-05 07:25 UTC, ajluk commented on styles/designs/cosmos/parts/_section-workscited-components.scss
> +    _name: "ParagraphhWithIndentation",
@kswanson33 Thank you for catching it up! :smile:

2021-10-05 14:10 UTC, kswanson33 approved these changes

2021-10-05 17:16 UTC, merged