Restyle chapter references for philosophy
openstax/cnx-recipes pull request #4291
Opened 2021-12-06 18:12 UTC by ajluk

For: #4289

2021-12-07 12:22 UTC, ajluk commented on styles/books/english-composition/book.scss
>  @include use('SectionWorksCited', 'cosmos:::SectionWorksCitedShape');
I have left this shape untouched because it contains titles with specific styling only for section Works Cited in Handbook a page: 
![image](https://user-images.githubusercontent.com/55203598/145027661-caaa81ab-9d24-47de-ab6f-8b419aedd60f.png)
If we would like these sections to utilize `ModuleWithIndentationShape` the titles need to be extracted from this shape or contains properties with OPTIONAL values set in book.scss file and I thought both solutions seems too much effort in this case, because this `SectionWorksCitedShape` is only used in English Composition.

2021-12-07 13:24 UTC, wilkus27 requested changes

2021-12-07 13:24 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +@include use('HandbookFurtherReading', 'cosmos:::ModuleWithIndentationShape');
I'm not sure about this. Handbook it's a EOB page like Appendix. This shape is for EOC sections. I think we should come to this later and create general shape for modules with indentations, that can be used for EOC and EOB. And probably it should be done in a separate PR.

2021-12-07 13:24 UTC, wilkus27 commented on styles/books/english-composition/book.scss
> +@include use('HandbookFurtherReading', 'cosmos:::ModuleWithIndentationShape');
Or add comment next to this shape in `eoc-shapes.scss` file that it should be moved out of EOC :thinking: All handbook fies are already removed, so maybe that make no sense to add them again :smile: But I would keep issue #4155 opened. We can add a comment there too.

2021-12-07 18:07 UTC, ajluk commented on styles/books/english-composition/book.scss
> +@include use('HandbookFurtherReading', 'cosmos:::ModuleWithIndentationShape');
@wilkus27 Thank you! I was going to move out the ModuleWithIndentationShape from EoC, but I just forgot at some point. I have move it out within the next commit. I will leave a comment in a clean up issue about it.

2021-12-08 09:21 UTC, wilkus27 approved these changes
Everything looks good :+1:

2021-12-08 10:30 UTC, merged