3952 math table spacing
openstax/cnx-recipes pull request #4335
Opened 2022-01-04 17:44 UTC by LostMojo

#3952

2022-01-04 21:20 UTC, LostMojo commented
<img width="551" alt="Screen Shot 2022-01-04 at 3 19 21 PM" src="https://user-images.githubusercontent.com/5740972/148125325-438e9682-617d-4f8c-8cad-b79ed85e332e.png">

2022-01-05 15:10 UTC, wilkus27 requested changes

2022-01-05 15:10 UTC, wilkus27 commented on styles/designs/corn/parts/_table-components.scss
> +        margin-top: table-v-spacing(1),
I think we should be more specific :thinking: There is no space between table and text in certain situations. This change is added to all tables. If table be after element with bottom padding (e.g para in module) there will be double space there (bottom padding of para and top padding of table).

2022-01-05 15:18 UTC, ajluk commented on styles/designs/corn/parts/_table-components.scss
> +        margin-top: table-v-spacing(1),
Natalia has already written what I'm concerned about as well. Maybe we can tag such tables with specific class in content and add top margins only to them? :thinking:

2022-01-06 17:32 UTC, LostMojo commented on styles/designs/corn/parts/_table-components.scss
> +        margin-top: table-v-spacing(1),
So I've changed it to only take effect in tables in lists-- but due to how the html is set up, there's not a way to always catch when there's not text above a list-bound table-- I think it should be fine.

2022-01-06 17:43 UTC, LostMojo commented on styles/designs/corn/parts/_table-components.scss
> +        margin-top: table-v-spacing(1),
I've limited created a different shape to only target tables in lists-- this should cover most of our bases, and Larissa says we probably don't have to worry too much about the edge case of a list item starting with a table!

2022-01-10 14:52 UTC, wilkus27 approved these changes

2022-01-10 15:06 UTC, merged