Update solution toggle styling
openstax/cnx-recipes pull request #4474
Opened 2022-02-10 17:22 UTC by bethshook

Updating baked styles to reflect style changes in this pr: https://github.com/openstax/rex-web/pull/1198/files

Would appreciate any feedback since I am new to the baked styles framework.

2022-02-10 18:14 UTC, bethshook commented on styles/output/_web-styles.json
> -[{"isBinary":false,"fileName":"biology-rex-web.css","originalFileName":"biology-rex-web.css","content":"@charset \"UTF-8\";\n@import url(\"https://fonts.googleapis.com/css?family=Alegreya:400,700&dis
not really sure what is happening here

2022-02-15 15:57 UTC, kswanson33 commented on styles/output/_web-styles.json
> -[{"isBinary":false,"fileName":"biology-rex-web.css","originalFileName":"biology-rex-web.css","content":"@charset \"UTF-8\";\n@import url(\"https://fonts.googleapis.com/css?family=Alegreya:400,700&dis
i am ... also not sure what is happening here. did that auto-generate when you rebuilt web styles?

2022-02-15 15:57 UTC, kswanson33 approved these changes

2022-02-16 08:56 UTC, wilkus27 requested changes

2022-02-16 08:56 UTC, wilkus27 commented on styles/designs/webview/parts/_exercise-components.scss
>    _name: "SolutionToggleVisible",
Small thing :wink: `_name` also should be changed to `SolutionToggleBefore`.

2022-02-16 08:56 UTC, wilkus27 commented on styles/designs/webview/parts/_exercise-components.scss
>    ),
Is it necessary to keep both these components? Second one has more specific selector, but the same property, so first one should cover also this case :thinking: Am I missing something?

2022-02-16 09:02 UTC, ajluk reviewed
Natalia has already mentioned everything I have also noticed. :slightly_smiling_face:

2022-02-17 00:08 UTC, bethshook commented on styles/output/_web-styles.json
> -[{"isBinary":false,"fileName":"biology-rex-web.css","originalFileName":"biology-rex-web.css","content":"@charset \"UTF-8\";\n@import url(\"https://fonts.googleapis.com/css?family=Alegreya:400,700&dis
yes but I can check it out if that seems wrong

2022-02-17 23:23 UTC, bethshook commented on styles/designs/webview/parts/_exercise-components.scss
>    ),
The less specific selector is what is used on rex but it was being overridden when I applied it via baked styles. I've removed it because I think now `.ui-toggle` will always be applied to a `summary` element.

2022-02-22 15:46 UTC, wilkus27 approved these changes
Beside problem with `web-styles.json` that Kendra mentioned, everything looks good :wink:

2022-02-22 23:07 UTC, bethshook commented on styles/output/_web-styles.json
> -[{"isBinary":false,"fileName":"biology-rex-web.css","originalFileName":"biology-rex-web.css","content":"@charset \"UTF-8\";\n@import url(\"https://fonts.googleapis.com/css?family=Alegreya:400,700&dis
I've removed this 👍

2022-03-28 16:26 UTC, merged