Update noteish elements styling
openstax/cnx-recipes pull request #4478
Opened 2022-02-15 01:46 UTC by bethshook

Updating baked styles to reflect style changes in this pr: https://github.com/openstax/rex-web/pull/1256/files

Would appreciate any feedback since I am new to the baked styles framework.

2022-02-15 16:03 UTC, LostMojo commented on styles/designs/webview/parts/_notes-components.scss
> +  _subselector: ' > *:not(section):not(header):first-child',
Do you want to include span[data-type=media] in this? This may overlap with the Media--InNote component below

2022-02-15 16:04 UTC, LostMojo commented on styles/designs/webview/parts/_notes-components.scss
> +  _subselector: ' > *:not(section):not(header):first-child',
Otherwise, this looks very good!

2022-02-16 09:21 UTC, ajluk commented on styles/designs/webview/parts/_notes-components.scss
> +    _name: "ExerciseContainerFirst",
A small thing, the name will be more descriptive if it will match the variable name: `FirstExerciseContainer`.

2022-02-16 09:23 UTC, wilkus27 requested changes

2022-02-16 09:23 UTC, wilkus27 commented on styles/designs/webview/parts/_learning-components.scss
> +  _name: "LearningObjectivesContainer",
Two components can't have the same `_name`. It also should be changed.

2022-02-16 09:23 UTC, wilkus27 commented on styles/output/webview-generic.css
> +
Padding is not changed. Probably because this component has the same name as the first one (see my previous comment). We will see what happen when you change the name. I'm afraid changing just padding won't be enough. Probably you should create two shapes. One for learning objectives as note and one for learning objectives in another tag (section?). And each of the shapes should contain all needed components with all properties.

2022-02-17 22:41 UTC, bethshook commented on styles/designs/webview/parts/_notes-components.scss
> +  _subselector: ' > *:not(section):not(header):first-child',
Good catch - Bartek didn't touch that so I think I will leave as is.

2022-02-22 15:37 UTC, wilkus27 approved these changes
Everything looks good :relaxed:

2022-03-28 16:26 UTC, merged