refactor eoc tables in corn & add DataTable to calc
openstax/cnx-recipes pull request #4521
Opened 2022-03-03 18:25 UTC by kswanson33

originally for #4501

needed to refactor eoc tables so that DataTable could be prioritized in eoc. more info in [slack thread](https://openstax.slack.com/archives/C022NETP39N/p1646323557058209)

2022-03-03 20:19 UTC, kswanson33 commented on styles/designs/corn/parts/_table-components.scss
> +$Table__Data--First--ColHeader: (
`DataTable` was looking funky because `Table__Data--First` is used in `BasicTableShape`, and includes some padding specifications that `DataTable` overrides. Seemingly though, `BasicTableShape` doesn't need the padding, and it's just used in `ColumnHeaderShape`. I dealt with this by separating `Table__Data--First` into 2 components, one to be used by `BasicTableShape` and one for `ColumnHeaderShape`, and removing the padding from the one for `BasicTableShape`.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/26280712/156645744-fcf65768-32cc-4edc-8aeb-b6f42f9b5182.png">
<img width="670" alt="image" src="https://user-images.githubusercontent.com/26280712/156645827-6c01e64e-ecdb-4fdd-b0f4-c31a97d8d20f.png">

2022-03-04 08:53 UTC, ajluk requested changes
I just left one comment in one place which concerns me. Everything else looks really good!

2022-03-04 08:53 UTC, ajluk commented on styles/design-settings/corn/parts/_table-settings.scss
> +      max-width: 100%,
@kswanson33 The above `Table` properties (`table-layout: fixed,
      max-width: 100%,`) were only used in ThreeColumnsModuleExercises, ReviewExercises, PrecticeTest, so only in exercises with three column layout. The values should be used only in tables in such exercises. A solution in this case could be to create two settings less genera for the EocTableShape  with different selectors and values for tables in exercises with different layout, f.ex.:  

```@include add_settings((
  EocTable--ThreeColumns: (
    _selectors: (
     '.os-eos.os-section-exercises-container > section [data-type="exercise"] [data-  type="problem"] .os-problem-  container > .os-table',
    '.os-eoc.os-review-exercises-container > section [data-type="exercise"] [data-  type="problem"] .os-problem-container > .os-table',
   'os-eoc.os-practice-test-container > section [data-type="exercise"] [data-  type="problem"] .os-problem-container > .os-table',
    ),
    EocTableContainer: (
      margin-left: 0,
      margin-right: 0,
    ),
    Table: (
      table-layout: fixed,
      max-width: 100%,
   ),
  )
));
```
```@include add_settings((
  EocTable--TwoColumns: (
    _selectors: (
     '..os-eos.os-section-exercises-container > section.section-exercises > section.writing [data-type="exercise"] [data-  type="problem"] .os-problem-container > .os-table',
    '..os-eos.os-section-exercises-container > section.section-exercises > section.everyday [data-type="exercise"] [data-  type="problem"] .os-problem-container > .os-table',
    ),
    EocTableContainer: (
      margin-left: 0,
      margin-right: 0,
    ),
  )
));
```
And used them adequately in books which have 3 or/and 2 column layout exercises.

2022-03-09 22:14 UTC, kswanson33 commented
@ajluk Thanks for your comment Anna! I decided to revert the tables to being nested under exercise modules, because I didn't realize the styles should be applied to such specific sections.

2022-03-10 15:05 UTC, ajluk commented on styles/design-settings/corn/parts/_exercises-settings.scss
> -            text-align: center
Same here.

2022-03-10 15:06 UTC, ajluk commented on styles/design-settings/corn/parts/_exercises-settings.scss
> -        ),
Also here.

2022-03-10 15:13 UTC, ajluk commented on styles/designs/corn/parts/_exercises-shapes.scss
> -                                                )),
And here.

2022-03-10 15:53 UTC, merged