rename appendix files carnival move font-size ul
openstax/cnx-recipes pull request #4624
Opened 2022-04-22 14:58 UTC by ajluk

for:  #4619

2022-05-05 09:25 UTC, wilkus27 requested changes
I left a few ideas. Let me know what do you think :wink:

2022-05-05 09:25 UTC, wilkus27 commented on styles/designs/cardboard/parts/_appendixglossary-components.scss
> +    margin-bottom: 0.7rem,
Maybe we should use `v-spacing(1)` here? It's better not to use hard coded values.

2022-05-05 09:25 UTC, wilkus27 commented on styles/designs/cardboard/parts/_lists-components.scss
> +  _name: "AppendixGlossaryGroupUnorderedList",
Can we remove part `Group` from the names? It appears in a few components.

2022-05-05 09:25 UTC, wilkus27 commented on styles/designs/cardboard/parts/_lists-components.scss
> +);
Strong tag is not part of a list. Can we move this component back to Appendix Glossary file? Maybe it could be named `AppendixGlossary__Term` :thinking:

2022-05-05 09:25 UTC, wilkus27 commented on styles/designs/cardboard/parts/_appendixglossary-components.scss
>  $Appendix--Glossary__Group: (
What do you think to change name everywhere from `Appendix--Glossary` to just `AppendixGlossary`? Previously there where some files/shapes for Appendices, but now we have only Appendix Glossary, so maybe we don't have to treat it as a type of Appendix :thinking:

2022-05-05 09:25 UTC, wilkus27 commented on styles/designs/carnival/parts/_appendixglossary-shapes.scss
> +            $H3--AppendixGlossary,
Titles are not imported to this file.

2022-05-05 09:25 UTC, wilkus27 commented on styles/designs/carnival/parts/_appendixglossary-shapes.scss
> +            $H3--AppendixGlossary,
And lists.

2022-05-05 16:39 UTC, ajluk commented on styles/designs/cardboard/parts/_lists-components.scss
> +);
Yes, that's right. I kept the name :slightly_smiling_face:

2022-05-05 16:39 UTC, ajluk commented on styles/designs/cardboard/parts/_appendixglossary-components.scss
>  $Appendix--Glossary__Group: (
Yes, good point!

2022-05-06 08:15 UTC, wilkus27 commented on styles/designs/carnival/parts/_appendixglossary-shapes.scss
> +            $H3--AppendixGlossary,
Hmm :thinking: That's interesting. What do you think to put this into cnx-recipes clean up epic https://github.com/openstax/cnx-recipes/issues/4635? I mean, to investigate this problem during that work?

2022-05-06 08:18 UTC, wilkus27 approved these changes

2022-05-06 09:17 UTC, merged