Docker Run migration
openstax/cnx-recipes pull request #4655
Opened 2022-05-06 20:43 UTC by LostMojo

#4621 

Changes the script/run command to use a single docker container to run commands.

2022-05-06 22:09 UTC, kswanson33 requested changes
The changes to `script/run` are looking good! I'll pull this branch down and test it locally, but to my knowledge it should work.

I'm wondering if we still need to worry about env vars. Do you ever use them? If not, it might be good to park this with the Katalyst folks & check

2022-05-06 22:09 UTC, kswanson33 commented on script/run
> +docker run -d -t --rm --mount type=bind,source="$PWD",target=/code --name runcontainer run-image /bin/bash
nice! runcontainer could also be named something like styles_container or styles_temp_container (more descriptive if you have multiple containers going)

2022-05-06 22:09 UTC, kswanson33 commented on script/run
> +docker stop runcontainer > /dev/null    # mutes "runcontainer" output
do we want to mute output?

2022-05-06 22:33 UTC, LostMojo commented on script/run
> +docker stop runcontainer > /dev/null    # mutes "runcontainer" output
Well, it usually just prints out its name, "runcontainer" which might be confusing to some folks. I just did this to clean it up a little, but if we want it, it can be unmuted

2022-05-06 22:34 UTC, LostMojo commented on script/run
> +docker run -d -t --rm --mount type=bind,source="$PWD",target=/code --name runcontainer run-image /bin/bash
ooo, good idea, changed

2022-05-06 22:55 UTC, LostMojo commented on Dockerfile
> -# dart pub get doesn't find the pubspec file until after the above line is run
hm, I'm not sure why it's not showing the restored file, but I know I did it :T for monday I guess

2022-05-09 17:37 UTC, kswanson33 commented
tested the container & all seems good :-) once extraneous files are removed, this can be merged! i'd recommend:

```bash
git rebase j.j    # brings this branch up to date. `git merge j.j` is another option
git reset --soft j.j
# Discard all chances except those to /script/run ...
git commit -m "..."
git push -f    # force push so that the commit tree will be clean on github as well as locally
```

2022-05-17 15:09 UTC, kswanson33 approved these changes

2022-05-17 15:10 UTC, merged